# Retries (pack 4): skeleton magus v1 drew the raised hand flames and the streaming ribbons past the edge of the disc
# (opaque radius 1.068, limit 0.867), so it could not be exported.
FIT = " Calibration from the previous generation of this exact token: the raised hand flames and the streaming ribbons reached past the edge of the disc, so the token could not be exported. This time draw the figure markedly smaller and tighter: the ENTIRE figure, both hand flames and every ribbon tip included, fits inside a circle of about two thirds of the disc radius around the disc centre, arms raised only to about shoulder height and angled slightly forward, ribbons short and wrapped close to the body, leaving a wide bare charcoal ring of base plate on every side."
retry('skeleton-magus', 4, comp=COMP + FIT)

# Retries (pack 5): elder vampire v1 raised the violet wisp beyond the disc edge (opaque radius 0.962, limit 0.867).
ELDER_FIT = " Calibration from the previous generation of this exact token: the raised hand and its violet magic wisp reached past the edge of the disc, so the token could not be exported. This time keep the raised hand low, only about chest height and close to the body, holding a small compact violet wisp no larger than a fist; the ENTIRE figure, wisp and hem included, fits inside a circle of about three quarters of the disc radius around the disc centre, leaving a wide bare charcoal ring of base plate on every side."
retry('elder-vampire', 5, comp=COMP + ELDER_FIT,
      palette="Mid-tone deep wine-plum robe (redder-purple than scarlet) lifted with lighter rose-mauve folds, violet magic wisp with a pale lilac core, pale skin and eyes; nothing darker than mid-dark except the cowl interior and hem seams; the magic must not cast violet light, glow or a cast onto the disc." + DISC)

# Retries (pack 6): forest wight v1 raised the axe head past the disc edge (opaque radius 0.877, limit 0.867).
WIGHT_FIT = " Calibration from the previous generation of this exact token: the raised axe head reached slightly past the edge of the disc, so the token could not be exported. This time hold the axe angled inward at shoulder height with the axe head close to the head, and keep the round shield close to the body; the ENTIRE figure, axe and shield included, fits inside a circle of about three quarters of the disc radius around the disc centre, leaving a wide bare charcoal ring of base plate on every side."
retry('forest-wight', 6, comp=COMP + WIGHT_FIT)

# Pack 7: grave wight call 1 never reached the image tool ("Selected model is at capacity", 7.8 s, no image, no result.json);
# the brief is unchanged. The call directory still counts against the budget.
retry('grave-wight', 7)

# Retries (pack 8): The Shade of Telos v1 let the crown, staff crystal and trailing robe pass the disc edge (opaque radius 0.940, limit 0.867).
SHADE_FIT = " Calibration from the previous generation of this exact token: the top of the crown, the staff crystal and the trailing robe wisps reached past the edge of the disc, so the token could not be exported. This time draw the figure markedly more compact: a shorter staff held close in front of the body with its crystal top at about head height, the robe hem wisps kept short around the base; the ENTIRE figure, crown, staff and robe included, fits inside a circle of about three quarters of the disc radius around the disc centre, leaving a wide bare charcoal ring of base plate on every side."
retry('shade-of-telos', 8, comp=COMP + SHADE_FIT)

# Packs 9-12: regenerations of drafts that passed the gate but were rejected on review (masked body luminance / size),
# not gate retries. Measured on the 128px export (alpha>=180, d<=0.55): vampire v1 42.8 and elder vampire v2 42.6 are below the
# 45 floor, ghoulking v1 50.8 reads dark on real floors, skeleton magus v2 draws a tiny figure (about half the disc width).
LIGHTER = " Calibration from the previous generation of this exact token: it was drawn too dark to read at 48px on a dark floor. This time the creature is clearly LIGHTER and more saturated in every lit plane while the disc stays exactly at the reference lightness: brighter mid-light body colours, strong lighter highlight planes on the upper-left of every fold and limb, no large black or near-black areas anywhere on the body."
retry('vampire', 9, comp=COMP + LIGHTER,
      subject="A vampire seen from a steep overhead three-quarter angle: a pale-faced dark-haired man with visible fangs crouching in a predatory lunge, wrapped in a wide flared BRIGHT vivid scarlet-red cape with a high collar, the cape lit with light coral-red highlight planes on every fold and lined only with a thin band of mid crimson (never black), a bright brick-red jacket underneath, one hand raised with curled claws, the other low, mid-grey-brown trousers and tan-brown boots. No staff, no hood. Menacing, predatory and complete, clearly lit.",
      palette="Bright vivid scarlet cape with light coral-red highlights, brick-red jacket, mid crimson lining, luminous pale skin, dark-brown hair, mid-grey-brown trousers, tan boots; the body is mid-light overall and nothing on it is near-black." + DISC)
retry('elder-vampire', 10, comp=COMP + ELDER_FIT.replace('about three quarters of the disc radius', 'about four fifths of the disc radius') + LIGHTER,
      subject="An elder vampire seen from a steep overhead three-quarter angle: a hooded figure in a long mid-light wine-rose robe with wide sleeves and a pale-gold rope belt, the cowl pulled up over a pale narrow face with pale glowing eyes and long thin fangs, one hand raised low holding a compact bright swirling wisp of violet magic, the other hand hidden in a sleeve, the hem of the robe brushing the base. No staff, no cape. Ancient, sinister and complete, clearly lit.",
      palette="Mid-light wine-rose robe lifted with much lighter rose-pink fold highlights, pale-gold belt, violet magic wisp with a pale lilac core, pale skin and eyes; the robe is mid-light overall with the cowl interior as the only dark area; the magic must not cast violet light, glow or a cast onto the disc." + DISC)
retry('ghoulking', 11, comp=COMP + LIGHTER,
      subject="A ghoulking seen from a steep overhead three-quarter angle: an upright broad-shouldered ghoul with leathery mid-light warm tan-brown skin (light saddle brown) lit with bright sand-tan highlights, standing wide-legged with both arms spread out and low, long pale bone-coloured claws on each hand, a heavy jaw with pointed teeth and glowing pale-yellow eyes, a bright polished gold crown of spikes on the brow, gold bands on the arms, a ragged brick-red loincloth. Regal, cruel and complete, clearly lit.",
      palette="Mid-light saddle-brown skin with bright sand-tan highlights, bright gold crown and arm bands, brick-red loincloth, pale bone claws, pale-yellow eyes; nothing on the body darker than mid-dark, only small seams; no glow or light cast onto the disc." + DISC)
GROW = " Calibration from the previous generations of this exact token: the first drew the hand flames and ribbons past the disc edge, the second was drawn tiny (about half the disc width). This time the figure fills about four fifths of the disc radius around the disc centre: arms raised to shoulder height and angled slightly forward, a flame in each hand held at about the width of the shoulders beyond the body, ribbons of moderate length wrapped around the body, leaving a clear bare charcoal ring of base plate on every side."
retry('skeleton-magus', 12, comp=COMP + GROW)

# Pack 13: skeleton magus v3 (four fifths of the disc radius, arms up in a V) again drew hand flames past the edge (opaque radius 1.018);
# v2 (two thirds) passed but was tiny. Design change: the arms are bent with both hands held in front of the shoulders and the flames
# burning just above the hands, so the figure grows vertically instead of sideways.
POSE = " Calibration from the previous generations of this exact token: with the arms raised in a wide V the hand flames reached past the disc edge (or, when drawn cautiously, the whole figure came out tiny). This time change the pose: both arms bent at the elbows, forearms raised, both open hands held in front of the shoulders about a hand-width apart, a small bright flame burning just above each hand, the ribbon sashes short and wrapped close around the ribs and hips. The figure is upright and compact and fills about three quarters of the disc radius around the disc centre, leaving a clear bare charcoal ring of base plate on every side."
retry('skeleton-magus', 13, comp=COMP + POSE,
      subject="A skeleton magus seen from a steep overhead three-quarter angle: a tall thin skeleton of warm ivory and pale gold bone standing upright and clearly open, with no cloak or hood, both arms bent with the forearms raised and the open hands held in front of the shoulders, a small bright orange-and-yellow flame burning just above each hand, a faint gold light in the eye sockets, short ribbon sashes of bright cobalt blue with pale-blue edges wrapping the ribcage and hips, small tarnished-gold trinkets on the wrists. Arcane, gaunt and complete.",
      contrast="Skeleton family: the shipped skeleton mage is a hunched figure wrapped in a dark cloak, the skeleton warrior is a steel-armoured sword bearer, the archer is a bare skeleton drawing a bow. The magus is the OPEN upright bare-boned figure with both hands raised in front of the shoulders and a flame above each hand, wrapped in cobalt-blue ribbons (silhouette: upright bare skeleton, two hand flames at shoulder height, no cloak; hue: ivory-gold bone with cobalt and orange accents; value: light).")

# Packs 14-16: review regenerations (all first calls already passed the gate). Reviewed at 48/64/96 colour and grayscale next to
# the shipped The Master: the elder vampire is another upright crimson-wine robe (lum 49.9) and reads as The Master without its staff;
# the master vampire is a dark navy column (lum 58.5, dark in grayscale); the forest wight is small and dark olive (lum 60.1).
BRIGHT = " Calibration from the previous generation of this exact token: it was drawn too dark and too small to read at 48px next to the other undead tokens. This time the creature is clearly LIGHTER, with strong light highlight planes on the upper-left of every fold, plate and limb, and it fills about four fifths of the disc radius around the disc centre (the figure and all its equipment stay inside that circle), while the disc stays exactly at the reference lightness."
retry('elder-vampire', 14, comp=COMP + BRIGHT,
      subject="An elder vampire seen from a steep overhead three-quarter angle: a hooded figure in a long mid-light plum-violet robe with wide sleeves and a pale-gold rope belt, the cowl pulled up over a pale narrow face with pale glowing eyes and long thin fangs, one hand raised low holding a compact bright swirling wisp of lilac-white magic, the other hand hidden in a sleeve, the hem of the robe brushing the base. No staff, no cape, no red anywhere. Ancient, sinister and complete, clearly lit.",
      contrast="Vampire family, four grades, plus the shipped The Master: the elder vampire is the HOODED PLUM-VIOLET robed figure with a lilac-white wisp in one hand (silhouette: pointed hood over a long conical robe, one raised hand; hue: plum-violet with pale gold; value: mid-light). The lesser vampire is an orange-tunic young man, the vampire a crouching scarlet-caped figure, the master vampire a tall indigo cloak, and the shipped The Master a crimson-red robe with a staff and no hood: the elder must NOT be red.",
      palette="Mid-light plum-violet robe lifted with much lighter lilac-mauve fold highlights, pale-gold belt, bright lilac-white magic wisp, pale skin and eyes; the robe is mid-light overall with the cowl interior as the only dark area; the magic must not cast light, glow or a cast onto the disc." + DISC)
retry('master-vampire', 15, comp=COMP + BRIGHT,
      subject="A master vampire seen from a steep overhead three-quarter angle: a tall gaunt pale-faced man with slicked dark hair and cold bright eyes, standing upright and calm in a long full-length cloak of bright cobalt royal blue with a high stiff collar lined pale sky-blue, the cloak lit with light periwinkle highlight planes on every fold, a large cream-white waistcoat and cravat clearly visible at the chest, mid-grey trousers, both arms hanging with long pale fingers. No staff, no fangs bared. Cold, aristocratic and complete, clearly lit.",
      palette="Bright cobalt royal-blue cloak lifted with light periwinkle folds and sky-blue lining, large cream-white waistcoat, pale skin, dark hair, mid-grey trousers; the cloak is mid-light overall and nothing on the body is near-black except the hair." + DISC)
retry('forest-wight', 16, comp=COMP + BRIGHT,
      subject="A forest wight seen from a steep overhead three-quarter angle: a gaunt skeletal undead warrior with bare pale-bone legs and arms, a skull face with two small red glowing eyes under a ragged lichen-green hood, a mid-light moss-green and pale-verdigris breastplate and shoulder pieces with hanging tatters and creeping ivy, a notched axe held angled at shoulder height in one hand and a round wooden shield with a bright bronze rim held in the other, faint pale-green wisps rising off the shoulders. Forsaken, wild and complete, clearly lit.",
      palette="Mid-light lichen and moss-green with pale-verdigris armour plates, bright pale bone limbs, small red eyes, warm tan wood shield with bronze rim, pale-green wisps; nothing darker than mid tone except the hood interior and armour seams; the wisps must not glow onto or tint the disc." + DISC)
