# Pack 5: snow giant v1 and snow giant boulder thrower v1 were accepted by eye but the disc rendered slightly DARKER than the reference
# (base_drift -8.16 and -9.04; tolerance +-8, no other blocking finding). Same design, disc calibration only.
DISC_LIGHTER = " Calibration from the previous generation of this exact token: the whole neutral disc came out slightly DARKER than the style reference (measured about 8 to 9 brightness units too dark, spread over the whole plate and worst in the outer ring band). This time render the entire disc, the outer ring band and the bevel included, visibly a touch LIGHTER and warmer-grey than the style reference's own plate, while keeping the creature exactly as described, the same pose, size and colours."
retry('snow-giant', 5, comp=COMP + FIT + GIANT + DISC_LIGHTER)
retry('snow-giant-boulder-thrower', 5, comp=COMP + FIT + GIANT + DISC_LIGHTER)

# Pack 6: minotaur v1 passed the gate (drift -4.73, lum 74.3) but read as a near twin of the shipped Minotaur of the Labyrinth at 48px:
# both are a warm brown bull-man with the axe hanging low on the left. Design change: pale piebald hide, head lowered, axe raised overhead.
MINO_DIFF = " Calibration from the previous generation of this exact token: it came out as a warm brown bull-man carrying an axe low on the left, which is too close to the shipped Minotaur of the Labyrinth. This time change the design: a pale cream-white and charcoal-black PIEBALD hide (large black patches like a dairy bull) with a short black mane, the head lowered and thrust forward in a charging stance, and the double-bladed axe raised in both hands ABOVE the shoulders, the haft held near the centre line with the blades at the top centre of the token, not hanging low. No brown fur, no brown skin."
retry('minotaur', 6, comp=COMP + FIT + GIANT + MINO_DIFF,
      subject="A minotaur seen from a steep overhead three-quarter angle: a hulking hunched bull-headed man with pale cream-white hide marked by large charcoal-black patches, a short black mane over the neck and shoulders, a bull head lowered and thrust forward with a flat pink muzzle, an iron nose ring, glaring pale eyes and two wide swept-back glossy black horns, a bare broad muscled chest with a studded black leather harness, a ragged grey loincloth, a double-bladed steel battle-axe lifted high in both hands with the blades near the top centre. Charging, brutish and complete.")

# Pack 7: minotaur v2 (piebald, axe overhead) was distinct but the raised axe blade crossed the disc rim (subject_intrusion +38.5, sectors 25-46);
# rejected, never shipped. Same piebald design, axe held horizontally across the chest, fully inside the disc.
MINO_FIT2 = " Calibration from the previous two generations of this exact token: (1) a brown minotaur with a low left axe was too close to the shipped Minotaur of the Labyrinth; (2) the piebald version lifted the axe so high that the blades crossed the outer rim of the disc. This time keep the pale cream and charcoal-black PIEBALD hide, the black mane and the lowered charging head, but hold the double-bladed axe HORIZONTALLY across the chest at chin height in both fists, with a SHORT haft so both blades stay well inside the disc, at least a sixth of the disc radius away from the disc edge. Nothing above the head. Draw the whole minotaur a little smaller so the horns, both axe blades, both feet and the loincloth all sit inside a circle of about two thirds of the disc radius."
retry('minotaur', 7, comp=COMP + FIT + GIANT + MINO_FIT2,
      subject="A minotaur seen from a steep overhead three-quarter angle: a hulking hunched bull-headed man with pale cream-white hide marked by large charcoal-black patches, a short black mane over the neck and shoulders, a bull head lowered and thrust forward with a flat pink muzzle, an iron nose ring, glaring pale eyes and two wide swept-back glossy black horns, a bare broad muscled chest with a studded black leather harness, a ragged grey loincloth, a short-hafted double-bladed steel battle-axe held horizontally across the chest in both fists with a blade at each side. Charging, brutish and complete.")
