# Retry packs are appended here (never edited in place).

# Pack 4: orc-berserker v1 (pack 2 call) failed the disc-geometry gate (max opaque radius 0.939, limit 0.867) and drew a subject_intrusion warning (+31.18): the two-handed axe raised high overhead reached far past the outer ring band. Same orc, axe held short and diagonal, figure smaller and pulled in.
OB_FIT = " Calibration from the previous generation of this exact token: the design (huge green orc in polished pale-steel massive plate, spiked pauldrons, horned helm, rust-red war-paint, crimson war-cloth, double-bladed battleaxe, no shield) was right, but the axe raised high overhead and the horns reached far out past the disc rim. This time keep the same orc, but draw it clearly SMALLER and more squat: the whole figure, horns, axe head and blades included, inside a circle of about 0.60 of the disc radius, centred, with a wide bare ring of plate on every side; hold the SHORT-hafted double-bladed battleaxe raised only to shoulder height at a diagonal beside the helm, both fists close to the head, the blades tucked in front of the shoulder and never above the horns, keep the crimson cloth tight to the hip and no cast shadow onto the plate."
_ob = next(a for a in A if a['id'] == 'orc-berserker')
retry('orc-berserker', 4, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + OB_FIT,
      subject=_ob['subject'].replace('raised HIGH OVERHEAD in both hands with bright steel blades', 'with a SHORT haft, raised only to shoulder height at a diagonal beside the helm in both fists, the bright steel blades tucked in front of the shoulder'))

# Pack 5: ogre-warmaster v1 (pack 2 call) passed the blocking gates but drew a subject_intrusion WARNING (+38.07, limit +20; the long swords stuck out to the lower right and upper left, the figure sat off-centre) and a base drift of +7.38 (limit +-8, disc lighter than the reference). Warnings are not shipped in this batch, so same design regenerated once: centred, swords short and tight, disc at reference lightness.
OW_FIT = " Calibration from the previous generation of this exact token: the design (tall armoured female ogre, gleaming silver-white plate with gold trim, crested visored helm with crimson plume, gold collar and greaves, crimson sash, two long swords) was right, but the two long swords stuck far out to one side and the figure stood off-centre, and the disc came out a little LIGHTER than the style reference. This time keep the same warmaster, but centre her exactly on the disc and draw her clearly SMALLER: the whole figure, plume and both swords included, inside a circle of about 0.60 of the disc radius, with a wide bare ring of plate on every side; both swords are held SHORT and vertical close against the body (one point-up in the fist at chest height with the tip no higher than the top of the helm crest, the other point-down beside the knee, tip no lower than the greaves), no sword angled outward, the plume swept back tight to the helm; no cast shadow. Render the whole disc, its outer ring band and the plate under the figure, at exactly the style reference lightness, evenly all round, never lighter."
retry('ogre-warmaster', 5, comp=COMP + FIT + COMPACT + BRIGHT + OW_FIT + CATS)

# Pack 6: barrow-wight v1 (pack 2 call) failed the base_drift gate (median -8.19, tolerance +-8): the sprawling shroud tatters and the mist round the legs darkened the plate, and the figure was muddy grey-green at small size. Same design, upright and compact, shroud tight, mist as a thin pale ring only, plate at reference lightness.
BW_FIT = " Calibration from the previous generation of this exact token: the design (gaunt undead in verdigris-and-bronze grave armour, bronze circlet, ice-blue eyes, pale shroud, cold witch-light and mist) was right, but the long shroud tatters and the blue mist spread over the disc and made the plate around the figure DARKER than the style reference, and the whole figure read as a muddy grey-green mass. This time keep the same wight, but stand it UPRIGHT and compact and draw it clearly SMALLER: everything inside a circle of about 0.60 of the disc radius, centred, with a wide bare ring of plate on every side; the shroud hangs tight against the body with short tatters that stay off the disc rim; the mist is only a THIN pale ring hugging the ankles, drawn as bright pale-blue wisps with NO dark halo, NO ambient darkening and NO cast shadow; make the armour BRIGHT polished verdigris-mint and bright bronze-gold, the face bone-white and the shroud near-white, so the figure is clearly light on the dark disc. Render the WHOLE disc, its outer ring band and the plate around the figure, at exactly the reference lightness or a hair lighter, evenly all round."
retry('barrow-wight', 6, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + BW_FIT + CATS)

# Pack 7: sanguine-horror v1 (pack 3 call) passed every style gate but its masked body luminance is 58.6 (project floor 65, review target 75): deep crimson blood is dark at 48px. Same design (rearing wave-column, glowing heart, two tendrils), value pushed up: bright scarlet-coral body with large pale-pink highlight planes.
SH_LIGHT = " LIGHT-VALUE REFINEMENT (the previous generation of this exact token was too dark at small size: deep crimson reads as a dark red stain): keep the same rearing wave-column with the glowing heart and the two dripping tendrils, but paint the blood as BRIGHT translucent SCARLET-CORAL and vivid orange-red with LARGE pale rose-pink and near-white highlight planes covering the whole upper-left half of the column, a BIG bright coral-white glowing heart, and a bright pale pink rim light along the entire outline; the darkest tone anywhere is a mid ruby-red, only in a few thin ripple seams; no maroon, no dark crimson, no black. Keep the whole figure inside a circle of about 0.66 of the disc radius, centred, no cast shadow, and the disc plate untouched at reference lightness."
_sh = next(a for a in A if a['id'] == 'sanguine-horror')
retry('sanguine-horror', 7, comp=COMP + FIT + COMPACT + BRIGHT + SH_LIGHT + CATS)

# Pack 8: orc-berserker pack 4 call returned no image (codex ended the turn without an image path; provenance-rejected, nothing stored). Same pack-4 brief re-run once (third and last call for this asset).
A.append(dict(next(a for a in A if a['id'] == 'orc-berserker' and a['pack'] == 4), pack=8))

# Pack 9: sanguine-horror pack 7 (v2) still measured a masked luminance of 60.8 (floor 65) and a base drift of -7.2: saturated red is dark by construction (pure red tops out near luminance 76). Third and last call for this asset: same wave-column, heart and tendrils, but the body is painted as a translucent SALMON-CORAL and rose-pink gel (like strawberry jelly) with red only in thin seams and a huge pale highlight, so the body mean is light.
SH_JELLY = " LIGHT-VALUE REFINEMENT 2 (two earlier generations of this exact token measured too dark because saturated red is dark at small size): keep the same rearing wave-column with the big glowing heart and the two dripping tendrils, but paint the whole body as translucent SALMON-CORAL and ROSE-PINK blood gel, like glossy strawberry jelly lit from behind: the dominant body colour is a light coral-pink (well lighter than the disc), with LARGE near-white pink highlight planes over the whole upper-left half and wet specular glints everywhere, a dazzling pale coral-white heart, and true red only as thin ripple seams and the drip tips; the darkest tone anywhere is a mid ruby-red in a few thin seams; no crimson mass, no maroon, no black, and no dark red around the base. Keep the figure inside a circle of about 0.62 of the disc radius, centred, with no cast shadow, no red spill and no puddle; the disc plate, its outer ring band and the plate under the figure stay exactly at the style reference lightness, evenly all round, never darker."
retry('sanguine-horror', 9, comp=COMP + FIT + COMPACT + BRIGHT + SH_JELLY + CATS)

# Pack 10 (coordinator-style 48px review, before shipping): barrow-wight v2 (pack 6) passes every numeric gate (masked luminance 95.8) but at 48px on real floors it is a busy mid-grey-green mass with a low-contrast face; third and last call for this asset. Same wight and same design, simplified into a few big light shapes.
BW_READ = " READABILITY REFINEMENT (the previous generation of this exact token passed the numeric gates but read as a busy muted grey-green mass at 48 pixels): keep the same gaunt armoured wight, but simplify it into a FEW BIG LIGHT SHAPES with strong local contrast: a bone-white skull-like face with two very bright ice-cyan eye glows and a bright GOLD circlet; big smooth bright MINT-VERDIGRIS pauldrons and breastplate with bright gold-bronze rims (fewer small plates, no fine engraving); a large near-white pale-blue burial CLOAK forming one clean triangular shape behind and beside the figure with only three or four long clean tatters; both arms forward with a bright ice-cyan witch-light glowing between the hands; only a very thin pale-cyan wisp at the ankles. Nothing grey-brown or murky anywhere, every large area either light mint, near-white, bone-white or bright gold; the figure is upright, centred, inside a circle of about 0.62 of the disc radius, with no cast shadow, no dark halo and the plate at exactly the reference lightness."
retry('barrow-wight', 10, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + BW_READ + CATS)
