# Retry packs are appended here (never edited in place).

# Pack 5: orb-weaver call-1 (pack 1) returned no image (codex ended the turn without an image path; provenance-rejected, nothing stored). Same brief re-run once.
retry('orb-weaver', 5)

# Pack 6: elven-elite-warrior v1 (pack 2 call) failed only the disc-geometry gate (max opaque radius 0.897, limit 0.867): the axe head, wing-crests and cape reached the outer ring band. Same design, figure smaller and pulled in.
EW_FIT = " Calibration from the previous generation of this exact token: the design (bronze-gold heavy plate, teal trim, winged helm with white plume, tower shield, double-bladed waraxe, teal cape) was right, but the axe head and the helm wing-crests reached too far out towards the disc rim (past the outer sixth ring band). This time keep the same elf, but draw it clearly SMALLER: the whole figure, axe head, plume, wing-crests, shield edge and cape included, inside a circle of about 0.60 of the disc radius, centred, with a wide bare ring of plate on every side; hold the waraxe SHORT and close against the shoulder (blade tips well inside), keep the cape tight to the back, and the shield in front of the body, not out to the side. No cast shadow onto the plate."
retry('elven-elite-warrior', 6, comp=COMP + FIT + COMPACT + BRIGHT + EW_FIT)

# Pack 7: void-horror v1 (pack 3 call) failed only the base_drift gate (median -8.78, tolerance +-8): the rift's dark surround and shards darkened the plate around it. Same design, rift smaller, plate at reference lightness.
VH_FIT = " Calibration from the previous generation of this exact token: the design (a vertical lens-shaped rift with a luminous silver-white border, indigo starfield, four-point flare, nebula ribbon, cracks and floating silver shards) was right, but the plate around the rift came out DARKER than the style reference (dark ambient shadow around the rift and its shards). This time keep the same rift, but draw it a little SMALLER (rift, cracks and shards all inside a circle of about 0.60 of the disc radius, centred, with a wide bare ring of plate on every side) with NO cast shadow, NO dark halo, NO ambient darkening and no smoke around it, and shards drawn as bright pale silver only. Render the WHOLE disc, its outer ring band and the plate around the figure, at exactly the reference lightness or a hair lighter, evenly all round; the rift's own interior stays a mid-indigo, never black."
retry('void-horror', 7, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + VH_FIT)

# Pack 8: runed-bone-giant v1 passed every blocking gate but drew a style WARNING (subject_intrusion +20.88 > +20: the raised arm and its glyph pushed one sector of the silhouette towards the rim). Warnings are not shipped in this batch, so same design regenerated once with the arm held low and the glyph ring even.
RB_FIT = " Calibration from the previous generation of this exact token: the design (aged cream-tan bone giant with glowing crimson rune glyphs, crimson eye pits, floating glyph ring, faint rose aura) was right, but the raised casting arm and its floating glyph pushed ONE side of the silhouette (upper right) much closer to the disc rim than the rest. This time keep the same giant, but hold BOTH arms LOW and close in front of the chest (the casting hand only at chest height, palm up with one glyph floating just above it), give the six floating glyphs one even small orbit at the same distance all round the body, and draw the whole figure clearly a little SMALLER and evenly round: everything inside a circle of about 0.62 of the disc radius, centred, with a wide bare ring of plate on every side, no cast shadow."
retry('runed-bone-giant', 8, comp=COMP + FIT + COMPACT + BRIGHT + RB_FIT + CATS)

# ---- Refinement pack (coordinator review of batch Z): rogue-sapper v1 passed every numeric gate (masked luminance 69.2) but the 48px review found a muddy brown blob on most floors (the same defect drem-master v1 was rejected for). Re-rolled through the declared refinement path; v1 stays as SUPERSEDED evidence.
def _pin(rel):
    return {'path': rel, 'sha256': sha(rel)}


_ZD = 'game/addons/tome-checker-revised/art/production/handoffs/monster-batch-z-1/'
_MZ = 'game/addons/tome-checker-revised/art/monster-batch-z/'
RS_LIGHT = " LIGHT-VALUE REFINEMENT (the previous version was rejected at 48 pixels: dark brown leather, brown cloth and brown boots merged into one muddy brown blob on the brown floors): draw the sapper in PALE SAND and LIGHT BONE-BEIGE linen (hood, face wrap and tunic) with LIGHT DOVE-GREY and pale tan-grey leather (straps, gloves, boots, satchel), a BRIGHT pale RIM LIGHT along the whole outline, BRIGHT POLISHED BRASS goggle rims with bright amber lenses, and a clearly visible BIG round pale-steel BOMB with a short lit fuse and a spark (held in one hand, close to the chest) plus a large light-grey leather SATCHEL bristling with a few bright steel spikes on the hip. The figure is compact and BIG: it fills the inner three quarters of the disc (about 0.7 of the disc radius across, centred, everything tucked inside), NOT thin. No brown mass, no dark brown, no black, no charcoal anywhere, only tiny eye shadows and thin seams; NO cast shadow, contact shadow or dark halo on the plate; render the whole disc, outer ring and plate under the figure at reference lightness, a hair lighter, never darker, evenly all round."
retry('rogue-sapper', 9, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + RS_LIGHT,
      subject="A rogue sapper seen from a steep overhead three-quarter angle: a compact CROUCHED sneaking rogue facing the lower left, a pulled-up hood and face wrap of PALE SAND and light bone-beige linen with bright cream highlight planes on every upper-left fold, round BRIGHT BRASS-RIMMED GOGGLES with amber lenses on the forehead, a light bone-beige tunic, a diagonal light-grey leather BANDOLIER studded with small polished BRASS SPRING-TRAPS, a big light-grey leather SATCHEL of trap parts on the hip with a few bright steel spikes sticking out, one gloved hand holding up close to the chest a BIG ROUND PALE-STEEL BOMB with a short lit fuse and a small orange spark, the other hand a short bright curved steel dagger held low, light tan-grey gloves and boots; no props on the ground. Crouched, sand-coloured, goggled, bomb-carrying and complete.",
      refinement={'supersedes': 'rogue-sapper', 'previous_batch': 'monster-batch-z-1',
                  'design_change_reason': "The first rogue sapper (khaki and olive-brown cloth, brown leather; masked luminance 69.2) passed the numeric style gate but the coordinator's 48px floor review found it a muddy brown blob on most floors. This refinement changes the value design, not just the roll: pale sand and bone-beige linen instead of dun khaki and olive-brown, light dove-grey leather instead of brown, bright brass goggles, a bright rim light, a large clearly visible pale-steel bomb with a lit fuse and a light-grey satchel, and a larger compact figure so the body mass is light; it stays a goggled trapper and not the assassin's slate-blue hooded lunger.",
                  'evidence': [_pin(_MZ + 'superseded/rogue-sapper-v1.png'), _pin(_ZD + 'rogue-sapper/imagegen-calls/call-1/call.json'), _pin(_ZD + 'rogue-sapper/receipts/attempt-1.json')]})
