# Retry packs are appended here (never edited in place).

# Pack 6: orc-high-pyromancer call 1 (pack 2) failed the disc-geometry gate (max opaque radius 0.941, limit 0.867): the two spread arms with their fireballs reached across the disc rim (the figure itself was right and bright). Same fire-lord, drawn smaller with the arms bent in.
PYRO_FIT = " Calibration from the previous generation of this exact token: the design (tall green orc fire-lord, scarlet-and-gold ceremonial robes, horned flame-crest mitre, gold flame pauldrons, fireballs in both hands, ring of fire at the waist) was right, but the spread arms and the two fireballs reached out across the disc rim. This time keep the same fire-lord, but draw everything clearly SMALLER: the whole figure, mitre, both fireballs and the fire ring inside a circle of about 0.58 of the disc radius, centred, with a wide bare ring of plate on every side; the arms are BENT at the elbows with the forearms raised close in front of the chest and a fireball held in each open hand right beside the shoulders (never spread out to the sides), and the ring of fire hugs the robe hem tightly; no cast shadow onto the plate."
_py = next(a for a in A if a['id'] == 'orc-high-pyromancer')
retry('orc-high-pyromancer', 6, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + PYRO_FIT,
      subject=_py['subject'].replace('with BOTH ARMS SPREAD WIDE and a roaring ball', 'with both arms bent and both forearms raised close in front of the chest and a roaring ball').replace('blazing in each open hand', 'blazing in each open hand right beside the shoulders'))

# Pack 7: orc-high-cryomancer call 1 (pack 2) failed the disc-geometry gate (max opaque radius 1.034, limit 0.867): the tall staff with its crystal and the ice-shard spiral crossed the disc rim (the figure itself was right and bright). Same frost-lord, drawn smaller with a short staff and a tight shard ring.
CRYO_FIT = " Calibration from the previous generation of this exact token: the design (tall green orc frost-lord, white and ice-blue robes with a white fur collar, tall crystal ice crown, jagged ice pauldrons, staff with a snowflake crystal, frost wand, spiral of ice shards) was right, but the tall staff with its crystal and the ice-shard spiral reached out across the disc rim. This time keep the same frost-lord, but draw everything clearly SMALLER: the whole figure, crown, staff, crystal and every shard inside a circle of about 0.58 of the disc radius, centred, with a wide bare ring of plate on every side; the staff is SHORT (only a little taller than his head, its snowflake crystal tucked beside the crown and never above it), the wand hand is held close to the chest, and the eight ice shards orbit tightly around the body at arm's length; no cast shadow onto the plate."
_cr = next(a for a in A if a['id'] == 'orc-high-cryomancer')
retry('orc-high-cryomancer', 7, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + CRYO_FIT,
      subject=_cr['subject'].replace('with a tall STAFF planted at his right side', 'with a SHORT STAFF planted close at his right side').replace('his left hand held out with', 'his left hand held close to the chest with').replace('a slow SPIRAL of eight', 'a tight SPIRAL of eight'))

# Pack 8: vampire-lord call 1 (pack 2) failed the disc-geometry gate (max opaque radius 1.008, limit 0.867): the raised rapier and the swept cloak crossed the disc rim (the noble himself was the right design). Same vampire lord, drawn smaller with a short blade and a cloak that hugs the body.
VL_FIT = " Calibration from the previous generation of this exact token: the design (tall pale noble, ochre-gold tunic with gold sash, bronze-brown crimson-lined cloak, raised rapier, red eyes) was right, but the raised rapier and the swept-out cloak reached across the disc rim. This time keep the same noble, but draw everything clearly SMALLER: the whole figure, blade and cloak inside a circle of about 0.58 of the disc radius, centred, with a wide bare ring of plate on every side; the rapier is a SHORT slim blade held diagonally close to the shoulder with its tip no higher than the top of the head, the cloak hangs close behind the shoulders and never sweeps out to the sides, the free hand is held close to the chest; no cast shadow onto the plate."
_vl = next(a for a in A if a['id'] == 'vampire-lord')
retry('vampire-lord', 8, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + VL_FIT,
      subject=_vl['subject'].replace('swept out behind his shoulders', 'hanging close behind his shoulders').replace('a slim bright steel RAPIER raised in the right hand at a diagonal', 'a SHORT slim bright steel RAPIER held close in the right hand at a diagonal').replace('the left hand held open with a small pale chill of frost', 'the left hand held close to the chest with a small pale chill of frost'))

# Pack 9: ungolmor call 1 (pack 2) returned no image path (codex reported no output; provenance-rejected, nothing stored). Same brief re-run once (second call for this asset).
A.append(dict(next(a for a in A if a['id'] == 'ungolmor' and a['pack'] == 2), pack=9))

# Pack 10: rotting-titan call 1 (pack 3) failed the base_drift gate (-9.02, tolerance +-8): the huge figure's shading darkened the disc plate (the figure itself was right and readable). Second call for this asset: same titan, drawn slightly smaller with the disc held at reference lightness.
DISC_LIFT = " DISC CALIBRATION (the previous generation of this exact token came out with the disc plate DARKER than the style reference, shadowed by the huge body): keep the same figure, but draw it a little SMALLER, everything inside a circle of about 0.55 of the disc radius, centred, and render the WHOLE disc, its outer ring band and the plate under and around the figure, at exactly the style reference lightness or a hair lighter, evenly all round, with no cast shadow, contact shadow, ambient occlusion or darkening beneath or beside the figure."
_rt = next(a for a in A if a['id'] == 'rotting-titan')
retry('rotting-titan', 10, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + CATS + TIGHT + DISC_LIFT, subject=_rt['subject'])

# Pack 11: oozing-horror call 1 (pack 4) wrote no structured result (codex returned nothing; no image, nothing stored). Same brief re-run once (second call for this asset).
A.append(dict(next(a for a in A if a['id'] == 'oozing-horror' and a['pack'] == 4), pack=11))

# Pack 12: ogric-abomination call 1 (pack 5) failed the base_drift gate (-10.64, tolerance +-8) and warned subject_intrusion: the raised maul and the big stone arm pushed out toward the rim and the plate around the heavy figure came out darker. Second call for this asset: same ogre, drawn smaller with the maul shortened and held close, the disc held at reference lightness.
OA_FIT = " Calibration from the previous generation of this exact token: the design (hulking grey-mauve ogre, one huge pale stone golem arm with violet-cyan runes, bolted stone plates, raised greatmaul) was right and readable, but the maul and the stone arm pushed out toward the disc rim and the plate came out darker than the reference. This time keep the same ogre, but draw it clearly SMALLER, everything inside a circle of about 0.55 of the disc radius, centred, with the greatmaul a SHORT-handled maul held diagonally close beside the head (its head no higher than the top of the head and no farther out than the shoulder) and the stone arm bent with the boulder fist held close in front of the chest; render the WHOLE disc, its outer ring band and the plate under and around the figure, at exactly the style reference lightness or a hair lighter, evenly all round, with no cast shadow, contact shadow or darkening beside the figure."
_oa = next(a for a in A if a['id'] == 'ogric-abomination')
retry('ogric-abomination', 12, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + CATS + TIGHT + OA_FIT,
      subject=_oa['subject'].replace('a big brown wooden GREATMAUL raised diagonally over the shoulder', 'a SHORT-handled brown wooden GREATMAUL held diagonally close beside the head').replace('ending in a boulder fist with glowing VIOLET-CYAN RUNES', 'bent with the boulder fist held close in front of the chest, glowing with VIOLET-CYAN RUNES'))

# Pack 13 (48px floor review, before shipping): vampire-lord pack-8 export passes every numeric gate (masked luminance 70.4, drift -2.66, radius 0.8585) but is the weakest figure on the real floors: small, and a dull mustard-brown mass with little value contrast. Third and last call for this asset. Same noble, brightened and drawn a little larger.
VL_READ = " READABILITY REFINEMENT (the previous generation of this exact token passed the numeric gates but read as a small dull mustard-brown mass at 48 pixels): keep the same noble, but lift every value and fill the disc better: a BRIGHT saffron-yellow and cream-gold long tunic with large near-white highlight planes and a broad bright gold sash, a bright pale face, a heavy cloak in warm light bronze-tan whose lining is a big bright vivid CRIMSON-RED panel clearly visible behind the shoulders, light tan boots, a bright silver-white rapier with a broad white edge highlight, and only the hair and eye slits dark; the figure fills the inner three quarters of the disc (a circle of about 0.68 of the disc radius, centred) as a bright shape on the dark plate, the rapier short and held close, the cloak hanging close behind; no dark brown or black cloth anywhere; render the whole disc and its plate at exactly the style reference lightness, with no cast shadow."
_vl2 = next(a for a in A if a['id'] == 'vampire-lord' and a['pack'] == 8)
retry('vampire-lord', 13, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + VL_FIT + VL_READ, subject=_vl2['subject'])
