# Retry packs are appended here (never edited in place).

# Pack 4: orc-elite-fighter call 1 (pack 2) returned no image ("Selected model is at capacity", provenance nothing stored). Same brief re-run once (second call for this asset).
A.append(dict(next(a for a in A if a['id'] == 'orc-elite-fighter' and a['pack'] == 2), pack=4))

# Pack 5: orc-summoner call 1 (pack 2) failed the disc-geometry gate (max opaque radius 1.003, limit 0.867): the tall totem staff and two of the spirit wisps crossed the disc rim (the figure itself was fine and bright). Same shaman, drawn smaller with a short staff and wisps hugging the body.
SUM_FIT = " Calibration from the previous generation of this exact token: the design (green orc beast-shaman, tawny spotted hide mantle, antler-and-tusk headdress, bone beads, feathered skull-topped totem staff, three turquoise-jade spirit wisps) was right, but the tall staff and two spirit wisps reached out across the disc rim. This time keep the same shaman, but draw everything clearly SMALLER: the whole figure, antlers, staff, feathers and all three wisps inside a circle of about 0.58 of the disc radius, centred, with a wide bare ring of plate on every side; hold a SHORT totem staff (a little taller than his head, staff head tucked beside the antlers and never above them), both hands close to the chest, and let the three small spirit wisps coil tight around the staff head and shoulders like smoke, none farther from the body than an arm's length; no cast shadow onto the plate."
_su = next(a for a in A if a['id'] == 'orc-summoner')
retry('orc-summoner', 5, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + SUM_FIT,
      subject=_su['subject'].replace('raising a tall wooden TOTEM STAFF', 'gripping a SHORT wooden TOTEM STAFF close to the chest').replace('coiling out of the staff head around him (all close to the body)', 'coiling tight around the staff head and shoulders like smoke (all close to the body)'))

# Pack 6: greater-mummy call 1 (pack 2) returned no image path (codex reported the tool call but no output; provenance-rejected, nothing stored). Same brief re-run once (second call for this asset).
A.append(dict(next(a for a in A if a['id'] == 'greater-mummy' and a['pack'] == 2), pack=6))

# Pack 7: greater-mummy pack-6 call (v1 candidate, not stored) failed the disc-geometry gate (max opaque radius 1.024, limit 0.867): the greatsword tip and the trailing linen ends crossed the disc rim (the figure itself was right). Third and last call for this asset: same mummy, sword shortened and held tight, figure smaller.
GM_FIT = " Calibration from the previous generation of this exact token: the design (tall gaunt mummy in clean ivory linen, striped blue-and-gold nemes headdress, turquoise-gold collar, bronze greatsword over the shoulder, frost-blue glowing palm) was right, but the greatsword tip and the loose linen ends reached out across the disc rim. This time keep the same mummy, but draw everything clearly SMALLER and tighter: the whole figure, headdress, sword and every linen end inside a circle of about 0.58 of the disc radius, centred, with a wide bare ring of plate on every side; the bronze greatsword is a SHORT broad blade held diagonally against the shoulder with its tip no higher than the top of the headdress and no farther out than the elbow; the loose wrapping ends are short and tucked against the body; the glowing palm is held close to the chest; no cast shadow onto the plate."
_gm = next(a for a in A if a['id'] == 'greater-mummy' and a['pack'] == 2)
retry('greater-mummy', 7, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + GM_FIT,
      subject=_gm['subject'].replace('a huge two-handed BRONZE GREATSWORD resting blade-up over the right shoulder', 'a SHORT broad BRONZE GREATSWORD held tight against the right shoulder').replace('with loose trailing ends', 'with only short tucked ends'))

# Pack 8 (coordinator-style 48px review, before shipping): orc-summoner pack-5 export passes every numeric gate (masked luminance 89.6, drift +1.87) but at 48px on real floors it is a muddy olive-brown mass with the teal wisps as its only readable part; third and last call for this asset. Same shaman, lightened into a few big light shapes.
SUM_READ = " READABILITY REFINEMENT (the previous generation of this exact token passed the numeric gates but read as a muddy olive-brown mass at 48 pixels): keep the same beast-shaman, but simplify it into a FEW BIG LIGHT SHAPES with strong local contrast: BRIGHT lime-green skin on the whole face, shoulders, arms and legs, a pale cream-and-honey spotted hide mantle with bright golden spots (no dark brown anywhere), big bone-white ANTLERS and a bone-white skull on the staff, a bright pale kilt of tan leather, bright red and turquoise feathers, and three LARGE glowing bright turquoise-jade spirit wisps with pale-white cores coiling around the staff head and shoulders so the teal glow forms one clear luminous shape beside the head; no dark leather straps, no brown-green shadow mass, no cast shadow. Keep the figure exactly as small as before: everything inside a circle of about 0.58 of the disc radius, centred, staff short."
_su2 = next(a for a in A if a['id'] == 'orc-summoner' and a['pack'] == 5)
retry('orc-summoner', 8, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + SUM_FIT + SUM_READ, subject=_su2['subject'])

# Pack 9 (coordinator-style 48px review): shadowblade v1 passes every numeric gate (masked luminance 77.7) but at 48px on real floors it is a dark navy-violet blob whose only readable part is the small silver X; second call for this asset. Same duellist, lightened.
SB_READ = " READABILITY REFINEMENT (the previous generation of this exact token passed the numeric gates but read as a dark navy-violet blob at 48 pixels): keep the same leaping twin-scimitar shadow-duellist, but lift every value: a BRIGHT pale periwinkle-and-sky-blue scarf and cloak with large near-white highlight planes, a light steel-blue tunic, a bone-white half-mask, light tan leather bracers and boots (no dark brown or black leather), two LARGE bright white-silver scimitars crossed in an X with broad white edge highlights, and only three thin lilac-violet shadow crescents (mid-lilac, never dark violet or black); the figure fills the inner three quarters of the disc as a bright shape on the dark plate; no cast shadow."
_sb = next(a for a in A if a['id'] == 'shadowblade')
retry('shadowblade', 9, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + SB_READ, subject=_sb['subject'])

# Pack 10: shadowblade pack-9 call (v2 candidate, not stored) read well and light but failed the base_drift gate (+9.96, tolerance +-8): the bright figure lifted the disc plate. Third and last call for this asset: same brightened duellist, drawn smaller, disc held at reference lightness.
SB_DISC = " DISC CALIBRATION (the previous generation of this exact token came out with the disc plate LIGHTER than the style reference): keep the same brightened duellist, but draw the whole figure clearly SMALLER, everything (scarf, blades, crescents) inside a circle of about 0.58 of the disc radius, centred, and render the WHOLE disc, its outer ring band and the plate under and around the figure, at exactly the style reference lightness, evenly all round, never lighter and never darker; the bright cloak must not brighten the plate around it."
retry('shadowblade', 10, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + SB_READ + SB_DISC, subject=_sb['subject'])
