"""R39 standee height table and archive contract (static).

The committed data/token-standee-heights.lua is generated by
tools/build_standee_heights.py from the native 64x128 shockbolt sprites. This
test re-runs the tool in --check mode and pins the native-tall/flat split, the
five kept standee ids and the archived layer files.
"""
import hashlib
import re
import subprocess
import sys
import unittest
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
TABLE = ROOT / 'data/token-standee-heights.lua'
TOKENS_LUA = ROOT / 'overload/mod/class/CheckerTokens.lua'
LAYER_DIR = ROOT / 'data/gfx/tokens-layer'
ARCHIVE = ROOT / 'art/token-layers'
BATCH_ARCHIVE = ARCHIVE / 'archive-native-flat-bosses'
HEIGHT_ARCHIVE = ARCHIVE / 'archive-flat-height'

# The native-tall ids whose effective cap is > 1.0 and that ship upright art.
# Read from the runtime module so a new standee is checked automatically; the
# layer/canvas checks below then cover it without editing this literal.
def _runtime_standee_ids() -> set:
    out = subprocess.run(['luajit', '-e',
                          "local T=assert(loadfile('overload/mod/class/CheckerTokens.lua'))() "
                          "local o={} for id in pairs(T.standee_ids) do o[#o+1]=id end table.sort(o) "
                          "io.write(table.concat(o,','))"],
                         cwd=ROOT, capture_output=True, text=True, check=True)
    return {tid for tid in out.stdout.strip().split(',') if tid}


KEPT = _runtime_standee_ids()
# Explicit floor (R46): the original four shipped standee ids must remain a
# subset of the runtime set, so a regression cannot silently drop one.
ORIGINAL_STANDEE_FLOOR = {'ninandra', 'ogre-guard', 'snow-giant', 'ravenous-horror'}
NATIVE_FLAT_BOSSES = {'rungof', 'grushnak', 'vor', 'phoenix', 'shardskin', 'subject-z'}
FLAT_BY_HEIGHT = {'gorbat', 'bone-giant'}
# R43: native-tall but the body-only cap is 1.0 (the axe blade is above a
# ~1-cell body); its standee layer and aura are archived.
BODY_FLAT_ARCHIVE = {'kra-tor'}
ARCHIVED = NATIVE_FLAT_BOSSES | FLAT_BY_HEIGHT | BODY_FLAT_ARCHIVE

EXPECTED_CAPS = {
    'kra-tor': 1.140625,
    'ravenous-horror': 1.25,
    'ninandra': 1.265625,
    'snow-giant': 1.40625,
    'ogre-guard': 1.421875,
}


def lua(expr: str) -> str:
    out = subprocess.run(['luajit', '-e', expr], cwd=ROOT, capture_output=True, text=True, check=True)
    return out.stdout.strip()


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _load_tool():
    import importlib.util
    spec = importlib.util.spec_from_file_location('build_standee_heights',
                                                  ROOT / 'tools' / 'build_standee_heights.py')
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _override_table() -> dict[str, float]:
    text = lua("local S=assert(loadfile('overload/mod/class/CheckerTokenStyle.lua'))() "
               "local o={} for k,v in pairs(S.standee_height_override) do o[#o+1]=k..'|'..v end "
               "table.sort(o) io.write(table.concat(o,'\\n'))")
    out = {}
    for line in text.splitlines():
        if line:
            key, value = line.split('|')
            out[key] = float(value)
    return out


class HeightTableTests(unittest.TestCase):
    def test_tool_reproduces_the_committed_table(self):
        done = subprocess.run([sys.executable, 'tools/build_standee_heights.py', '--check'],
                              cwd=ROOT, capture_output=True, text=True)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertIn('151 native-tall ids', done.stdout)

    def test_table_shape_and_flat_split(self):
        self.assertTrue(TABLE.is_file())
        header = TABLE.read_text().splitlines()[0]
        self.assertIn('tools/build_standee_heights.py', header)
        counts = lua("local t=assert(loadfile('data/token-standee-heights.lua'))() "
                     "local n,f=0,0 for _,v in pairs(t) do n=n+1 if v<=1.0 then f=f+1 end end "
                     "io.write(n..'|'..f)")
        total, flats = (int(v) for v in counts.split('|'))
        self.assertEqual(total, 151, '151 native-tall ids')
        self.assertEqual(flats, 31, '31 native-tall ids are flat (cap 1.0)')

    def test_committed_caps_and_flat_markers(self):
        for tid, cap in EXPECTED_CAPS.items():
            got = lua("local t=assert(loadfile('data/token-standee-heights.lua'))() "
                      f"io.write(tostring(t[{tid!r}]))")
            self.assertEqual(float(got), cap, tid)
        for tid in ('gorbat', 'bone-giant', 'lich', 'ancient-lich'):
            got = lua("local t=assert(loadfile('data/token-standee-heights.lua'))() "
                      f"io.write(tostring(t[{tid!r}]))")
            self.assertEqual(float(got), 1.0, tid)
        for tid in ('phoenix', 'rungof', 'wolf'):
            got = lua("local t=assert(loadfile('data/token-standee-heights.lua'))() "
                      f"io.write(tostring(t[{tid!r}]))")
            self.assertEqual(got, 'nil', tid)

    def test_tool_rejects_unknown_review_ids(self):
        import unittest.mock as mock
        mod = _load_tool()
        self.assertIn('elandar', mod.MANUAL_HEIGHT_REVIEW)
        self.assertNotIn('elander', mod.MANUAL_HEIGHT_REVIEW)
        with mock.patch.object(mod, 'MANUAL_HEIGHT_REVIEW',
                               mod.MANUAL_HEIGHT_REVIEW + ('not-a-real-id',)):
            with self.assertRaises(SystemExit):
                mod.compute()

    def test_runtime_overrides_are_reviewed_and_reduce_the_cap(self):
        mod = _load_tool()
        overrides = _override_table()
        self.assertTrue(overrides, 'at least one reviewed id needs a height override')
        reviewed = set(mod.MANUAL_HEIGHT_REVIEW)
        self.assertTrue(set(overrides) <= reviewed, 'every override key is in the tool review list')
        # ogre-guard (floating top speck) and the raised-weapon/effect ids.
        self.assertIn('ogre-guard', overrides)
        self.assertIn('arch-zephyr', overrides)
        # The remaining standee with a weapon in its master keeps the derived
        # cap; kra-tor is flat and ogre-guard trims its hammer/speck. ninandra
        # is a shipped standee too, but its head glow is trimmed (no exemption).
        self.assertEqual(overrides['kra-tor'], 1.0, 'kra-tor axe over a ~1-cell body is flat')
        self.assertEqual(overrides['ogre-guard'], 1.078125, 'ogre-guard hammer + speck trimmed (head top y=43)')
        self.assertEqual(overrides['ninandra'], 1.140625, 'ninandra head glow trimmed (alpha>128 top y=38)')
        for tid in ('snow-giant', 'ravenous-horror'):
            self.assertNotIn(tid, overrides, tid)
        heights = {}
        for line in lua("local t=assert(loadfile('data/token-standee-heights.lua'))() "
                        "local o={} for k,v in pairs(t) do o[#o+1]=k..'|'..v end io.write(table.concat(o,'\\n'))").splitlines():
            if line:
                key, value = line.split('|')
                heights[key] = float(value)
        for tid, value in overrides.items():
            self.assertLessEqual(value, heights[tid], tid)
            self.assertGreaterEqual(value, 1.0, tid)
            self.assertLessEqual(value, 1.75, tid)

    def test_r42_body_only_corrections(self):
        mod = _load_tool()
        overrides = _override_table()
        # Body parts count: the minotaur's horns and walrog's head water-horns
        # keep the generated cap instead of a weapon trim.
        for tid in ('minotaur-maze', 'walrog'):
            self.assertNotIn(tid, overrides, tid)
        # R41 overrides dropped because the bbox top is body under the new rule.
        for tid in ('thaurhereg', 'harkor-zun', 'spellblaze-simulacrum',
                    'corrupted-sand-wyrm', 'rotting-titan',
                    'temporal-defiler', 'prox'):
            self.assertNotIn(tid, overrides, tid)
        # Raised weapons/staves/spells/particles/flames/lightning do not count.
        for tid in ('lady-nashva', 'caldizar', 'argoniel', 'ogre-rune-spinner',
                    'snow-giant-thunderer', 'pale-drake', 'forge-giant',
                    'boiling-horror', 'xhaiak-arachnomancer'):
            self.assertIn(tid, overrides, tid)
        self.assertEqual(overrides['lady-nashva'], 1.234375)
        self.assertEqual(overrides['caldizar'], 1.25)
        self.assertEqual(overrides['argoniel'], 1.0)
        self.assertEqual(overrides['ogre-rune-spinner'], 1.296875)
        self.assertEqual(overrides['snow-giant-thunderer'], 1.40625)
        self.assertEqual(overrides['pale-drake'], 1.0)
        self.assertEqual(overrides['forge-giant'], 1.328125)
        self.assertEqual(overrides['lady-zoisla'], 1.3125)
        self.assertEqual(overrides['snow-giant-boulder-thrower'], 1.484375)
        self.assertEqual(overrides['celia'], 1.390625)
        self.assertEqual(overrides['naga-tidecaller'], 1.078125)
        self.assertEqual(overrides['xhaiak-arachnomancer'], 1.4375)
        self.assertEqual(overrides['boiling-horror'], 1.0)
        # R44 colour sweep: the top rows are an effect, not the body.
        self.assertEqual(overrides['burb-snow-giant-champion'], 1.53125)
        self.assertEqual(overrides['gigantic-gravity-worm'], 1.40625)
        self.assertEqual(overrides['gigantic-sandworm-tunneler'], 1.40625)
        self.assertEqual(overrides['heavy-sentinel'], 1.546875)
        self.assertEqual(overrides['uruivellas'], 1.296875)
        # R45 sparse or semi-transparent fringes (bristles, specks, mist,
        # darkness shroud, warm glow) are not body: the solid mass top is used.
        self.assertEqual(overrides['archmage-tarelion'], 1.0)
        self.assertEqual(overrides['duathedlen'], 1.265625)
        self.assertEqual(overrides['onilug'], 1.015625)
        self.assertEqual(overrides['weaver-queen'], 1.234375)
        # ogre-warmaster's alpha top is the helmet, so the derived cap is kept.
        self.assertNotIn('ogre-warmaster', overrides)
        self.assertEqual(overrides['norgos-frozen'], 1.359375)
        self.assertEqual(overrides['ak-gishil'], 1.34375)
        # R45/R46 reviewed overrides; ninandra joins in R46; R48 adds the
        # half-finished bone giant purple halo and the kryl-feijan darkness.
        self.assertEqual(len(overrides), 49)
        self.assertEqual(overrides['half-finished-bone-giant'], 1.21875)
        self.assertEqual(overrides['kryl-feijan'], 1.0)
        self.assertGreaterEqual(len(mod.MANUAL_HEIGHT_REVIEW), 50)
        for tid in ('geomancer', 'tempest', 'cryomancer', 'lady-nashva',
                    'ogre-rune-spinner', 'xhaiak-arachnomancer'):
            self.assertIn(tid, mod.MANUAL_HEIGHT_REVIEW, tid)
            self.assertIn(tid, overrides, tid)

    def test_energy_bodies_keep_the_derived_cap(self):
        # Decision 3 (R46, extended R48): for these cloud/energy/elemental beings
        # the glow, cloud or element IS the body, so the derived cap is kept and
        # no override applies. The reasons quote the native desc so the decision
        # is not a bare assertion.
        overrides = _override_table()
        mod = _load_tool()
        heights = dict(mod.compute()[0])
        expected = {
            'greater-telugoroth': 1.1875, 'ultimate-telugoroth': 1.609375,
            'daelach': 1.71875, 'fyrk': 1.59375, 'ultimate-faeros': 1.34375,
            'ultimate-teluvorta': 1.640625, 'maelstrom': 1.71875,
            'ultimate-gwelgoroth': 1.375, 'glacial-legion': 1.671875,
        }
        for tid, cap in expected.items():
            self.assertNotIn(tid, overrides, tid)
            self.assertEqual(heights[tid], cap, tid)
        text = (ROOT / 'docs' / 'standee-body-review.md').read_text()
        for phrase in ('blurred form', 'cloud of fiery darkness', 'fire elementals',
                       'time elemental', 'vortex of ice and lightning',
                       'air elementals', 'shifting, ethereal form'):
            self.assertIn(phrase, text)

    def test_body_review_doc_is_complete(self):
        # The full 151-id table (id, derived, final, reason) is committed.
        text = (ROOT / 'docs' / 'standee-body-review.md').read_text()
        self.assertIn('Native-tall ids: **151**', text)
        self.assertIn('reviewed overrides: **49**', text)
        final_flats = int(lua("local S=dofile('overload/mod/class/CheckerTokenStyle.lua') "
                              "local n=0 for id in pairs(S.standee_heights) do "
                              "if S.standeeHeight(id)<=1 then n=n+1 end end io.write(n)"))
        self.assertEqual(final_flats, 53, 'final split includes runtime overrides')
        self.assertIn(f'flat (final 1.0): **{final_flats}**', text)
        self.assertEqual(text.count('\n| `'), 151)
        for tid in ('thaurhereg', 'harkor-zun', 'prox', 'corrupted-sand-wyrm',
                    'lady-nashva', 'caldizar', 'argoniel', 'ogre-rune-spinner'):
            self.assertIn('| `' + tid + '` |', text)

    def test_override_reason_y_matches_the_value(self):
        # A reason that quotes a head/horn top "y=NN" must reproduce the
        # override: clamp((bottom - y + 1)/64 - 0.25, 1.0, 1.75). This is the
        # R44/R46 convention and the reason strings cannot drift from the numbers.
        # The clamp matters for archmage-tarelion (solid top y=49 -> 0.96875 ->
        # flat 1.0) and any other body-only top below one cell.
        import re as _re
        mod = _load_tool()
        entries = dict(mod.parse_catalogue(TOKENS_LUA.read_text()))
        block = _re.search(r'M\.standee_height_override=\{(.*?)\n\}',
                           (ROOT / 'overload/mod/class/CheckerTokenStyle.lua').read_text(),
                           _re.S).group(1)
        checked = 0
        for m in _re.finditer(r"\['([^']+)'\]\s*=\s*([0-9.]+),\s*--[^\n]*?y=(\d+)", block):
            tid, value, y = m.group(1), float(m.group(2)), int(m.group(3))
            metrics = mod.alpha_metrics(mod.SPRITES / entries[tid])
            bottom = metrics['top'] + metrics['height_px'] - 1
            derived = mod.clamp((bottom - y + 1) / 64 - 0.25, mod.HEIGHT_MIN, mod.HEIGHT_MAX)
            self.assertAlmostEqual(derived, value, places=9, msg=tid)
            checked += 1
        self.assertGreaterEqual(checked, 10, 'the y-quoting reasons are checked')

    def test_doc_final_values_match_style(self):
        # The docs table's FINAL column is the product lookup, not a copy that
        # can drift: every one of the 151 ids must equal Style.standeeHeight(id).
        text = (ROOT / 'docs' / 'standee-body-review.md').read_text()
        finals = {}
        for m in re.finditer(r'\| `([^`]+)` \| [0-9.]+ \| ([0-9.]+) \|', text):
            finals[m.group(1)] = float(m.group(2))
        self.assertEqual(len(finals), 151)
        out = lua("local S=assert(loadfile('overload/mod/class/CheckerTokenStyle.lua'))() "
                  "local o={} for id in pairs(S.standee_heights) do o[#o+1]=id..'|'..S.standeeHeight(id) end "
                  "table.sort(o) io.write(table.concat(o,'\\n'))")
        runtime = {}
        for line in out.splitlines():
            if line:
                key, value = line.split('|')
                runtime[key] = float(value)
        self.assertEqual(set(runtime), set(finals))
        for tid, value in finals.items():
            self.assertAlmostEqual(runtime[tid], value, places=9, msg=tid)

    def test_tool_rejects_an_unreviewed_or_excessive_override(self):
        import unittest.mock as mock
        mod = _load_tool()
        heights, _ = mod.compute()
        caps = dict(heights)
        # An id that is not in the review list is rejected.
        with self.assertRaises(SystemExit):
            mod.check_overrides({'not-reviewed': 1.1}, caps)
        # An override above the generated cap is rejected (ogre-warmaster is
        # reviewed, cap 1.390625).
        with self.assertRaises(SystemExit):
            mod.check_overrides({'ogre-warmaster': 1.99}, caps)
        # An override outside the clamp range is rejected.
        with self.assertRaises(SystemExit):
            mod.check_overrides({'minotaur-maze': 0.5}, caps)

    def test_kept_ids_ship_256px_art(self):
        # KEPT is read from the runtime module, so asserting ids == KEPT would
        # be self-referential (same source on both sides). Instead require the
        # explicit original-four floor, and check every shipped id is natively
        # tall with a > 1.0 cap and really ships its 256px layer file.
        self.assertTrue(KEPT, 'at least one standee ships')
        self.assertTrue(ORIGINAL_STANDEE_FLOOR <= KEPT,
                        'the original four standee ids still ship: %r' % (ORIGINAL_STANDEE_FLOOR - KEPT))
        for tid in sorted(KEPT):
            self.assertTrue((LAYER_DIR / (tid + '.png')).is_file(), tid)
            cap = lua("local S=assert(loadfile('overload/mod/class/CheckerTokenStyle.lua'))() "
                      "io.write(tostring(S.standeeHeight(%r)))" % tid)
            self.assertNotEqual(cap, 'nil', tid)
            self.assertGreater(float(cap), 1.0, tid)


class ArchiveTests(unittest.TestCase):
    def test_archived_layer_files_are_gone(self):
        for tid in ARCHIVED:
            self.assertFalse((LAYER_DIR / (tid + '.png')).exists(), tid)

    def test_kept_layer_files_are_256px(self):
        for tid in sorted(KEPT):
            with Image.open(LAYER_DIR / (tid + '.png')) as im:
                self.assertEqual(im.size, (256, 256), tid)

    def test_masters_are_archived_with_provenance(self):
        for tid in NATIVE_FLAT_BOSSES:
            self.assertTrue((BATCH_ARCHIVE / tid / 'master-v1.png').is_file(), tid)
        for tid in FLAT_BY_HEIGHT:
            self.assertTrue((HEIGHT_ARCHIVE / tid / 'master-v1.png').is_file(), tid)
        for readme in (BATCH_ARCHIVE / 'README.md', HEIGHT_ARCHIVE / 'README.md',
                       ARCHIVE / 'archive-flat-body' / 'README.md'):
            self.assertTrue(readme.is_file(), readme)
        text = (BATCH_ARCHIVE / 'README.md').read_text()
        self.assertIn('native tall only', text)
        # R43: kra-tor's layer and aura are archived with the master.
        for name in ('master-v1.png', 'layer-256.png', 'aura-256.png'):
            self.assertTrue((ARCHIVE / 'archive-flat-body' / 'kra-tor' / name).is_file(), name)
        # The archived masters keep the R36 review hashes.
        self.assertTrue(sha(BATCH_ARCHIVE / 'rungof' / 'master-v1.png').startswith('a5d85c59ee3a1b17'))
        self.assertTrue(sha(HEIGHT_ARCHIVE / 'gorbat' / 'master-v1.png').startswith('c726ef66a1bcc3f6'))
        self.assertTrue(sha(ARCHIVE / 'archive-flat-body' / 'kra-tor' / 'master-v1.png').startswith('3bca69c571c46106'))
        # A re-run of the build tool must not resurrect a standee directory.
        for tid in ARCHIVED:
            self.assertFalse((ARCHIVE / tid / 'standee').exists(), tid)


if __name__ == '__main__':
    unittest.main()
