# Retry packs are appended here (never edited in place).

# Pack 5: fiery-orc-wyrmic v1 produced no recorded output (codex reported an empty image path, provenance rejected; the call still counts). Same brief, unchanged apart from a calibration line.
FO_FIT = " Calibration: return the finished image and its file path. Keep the design exactly as briefed and the whole figure, axe and flame included, inside the inner three quarters of the disc. Render the WHOLE disc, its outer ring band and the plate under the figure, at reference lightness, a hair lighter, never darker, evenly all round, with NO cast shadow and no ambient darkening of the disc from the creature, and no fire glow on the plate."
retry('fiery-orc-wyrmic', 5, comp=COMP + FIT + COMPACT + BRIGHT + FO_FIT)

# Pack 6: fiery-orc-wyrmic v1 (pack 5) failed only the disc-overflow gate (max opaque radius 0.9798 > 0.867; base_drift +0.05, intrusion 3.17 passed): the axe head at the upper left crossed the disc rim and the export was shrunk around it. Same design, SHORT axe held close, everything inside the inner two thirds.
FO2_FIT = " Calibration from the previous generation of this exact token: the design, the crimson-orange scale armour and the wide stance were right, but the battleaxe stuck OUT of the disc across the rim at the upper left. This time keep the same olive-green tusked orc in bright crimson-orange dragon-scale armour with red wing-fin pauldrons, horned bone-and-gold helm and a small flame in the open left hand, but hold a SHORT-HANDLED hand axe (haft no longer than the orc's forearm, a modest steel head) raised in the right hand at shoulder height, angled up and out to the RIGHT, the axe head at least one full head-height inside the disc rim and NOT above the head, with both elbows kept in close to the body. Put the figure exactly in the centre of the disc, the WHOLE figure including axe and flame inside a circle of about two thirds of the disc radius with a wide bare ring of plate on every side, nothing whatsoever touching or crossing the disc rim. Render the WHOLE disc, its outer ring band and the plate under the figure, at reference lightness, a hair lighter, never darker, evenly all round, with NO cast shadow and no ambient darkening of the disc from the creature, and no fire glow on the plate."
retry('fiery-orc-wyrmic', 6, comp=COMP + FIT + COMPACT + BRIGHT + FO2_FIT,
      subject=next(a for a in A if a['id'] == 'fiery-orc-wyrmic')['subject'].replace('the RIGHT ARM raises a broad battleaxe DIAGONALLY UP AND OUTWARD over the shoulder toward the upper right (bright steel axe head with an orange fire glint, the haft short and the axe head well inside the disc)', 'the RIGHT ARM holds a SHORT-HANDLED steel hand axe at shoulder height angled up and out to the right (a small orange fire glint on the head, the whole axe well inside the disc)'))

# Pack 7: giant-ice-ant v1 failed only the base_drift gate (median +8.02, tolerance +-8; radius 0.8585 and intrusion 3.64 passed): the pale frost and snow crystals made the plate around the ant come out LIGHTER than the reference. Same design, slightly smaller, frost and snow kept off the plate, disc at exactly reference lightness.
IA_FIT = " Calibration from the previous generation of this exact token: the design and colours were right, but the plate around the pale frost came out LIGHTER than the style reference (frost glow and snow crystals spilled onto the disc). This time keep the same crystalline pale-cyan ice ant with the crest of five short ice spikes, but draw it a little SMALLER (the whole ant inside a circle of about two thirds of the disc radius, centred, with a wide bare ring of plate on every side) with NO snow crystals, NO mist and NO frost glow off the body. Render the WHOLE disc, its outer ring band and the plate under and around the ant, at exactly the reference lightness, neither lighter nor darker, evenly all round, warm-neutral mid charcoal, with NO bright halo, no cast shadow and no ambient change of the disc from the ant or the ice."
retry('giant-ice-ant', 7, comp=COMP + FIT + COMPACT + BRIGHT + IA_FIT,
      subject=next(a for a in A if a['id'] == 'giant-ice-ant')['subject'].replace(', a few tiny snow crystals drifting close to the body', ''))

# Pack 8: giant-ice-ant pack 7 produced no recorded output (codex reported an empty image path, provenance rejected; the call still counts). Same brief as pack 7 plus the return-the-path line.
retry('giant-ice-ant', 8, comp=COMP + FIT + COMPACT + BRIGHT + IA_FIT + " Return the finished image and its file path.",
      subject=next(a for a in A if a['id'] == 'giant-ice-ant' and a['pack'] == 7)['subject'])
