# Retry packs are appended here (never edited in place).

# Pack 5: naga-psyren v1 failed only the base_drift gate (median -9.08, tolerance +-8; radius 0.8585 and intrusion 5.16 passed, no other blocking item): the disc came out darker than the reference, most under the wide-spread rose hair, and the hair itself ran out to the rim. Same design, hair gathered in close, disc at reference lightness with no cast shadow.
PSY_HAIR = " Calibration from the previous generation of this exact token: the design was right, but the base disc came out DARKER than the style reference (especially under and around the long rose hair) and the hair spread out wide to the rim. This time keep the same serene violet-spiral-tailed siren with the glowing purple-white orb held in both hands, but pull the rose-pink hair in close: it falls in two thick soft waves over her shoulders and ends at about waist height, gathered and tucked, never spreading out to the sides like wings and never reaching the outer ring band. Render the WHOLE disc, its outer ring band and the plate under the hair and tail, at reference lightness, a hair lighter, never darker, evenly all round, with NO cast shadow, no dark contact shadow and no ambient darkening of the disc from the creature or its hair."
retry('naga-psyren', 5, comp=COMP + FIT + COMPACT + BRIGHT + PSY_HAIR,
      subject=next(a for a in A if a['id'] == 'naga-psyren')['subject'].replace('long flowing ROSE-PINK hair spreading out to both sides like soft wings', 'thick ROSE-PINK hair falling in two soft waves over the shoulders and gathered close to the body'))

# Pack 6: orc-master-assassin v1 passed the numeric gate (base_drift -7.08, radius 0.8621) but the visual review rejected it: the tall red topknot and the raised dagger points crossed the disc rim, so the 128px export shrank and off-centred the disc (bbox placement), and the disc looked darker than the reference. Same design, all anatomy strictly inside the inner three quarters, topknot as a short low tied tail, disc at reference lightness.
OMA_FIT = " Calibration from the previous generation of this exact token: the design was right, but the tall red topknot stuck up OUT of the disc across the rim at the top and the dagger tips reached the ring band, and the disc came out slightly darker than the reference. This time keep the same bare-headed olive-green orc facing the viewer in a wide low stance with two daggers crossed in an X in front of the chest, but draw the figure SMALLER and LOWER in the disc: the hair is a SHORT LOW TIED PONYTAIL hanging behind the head (no tall topknot, nothing rising above the head by more than a hand's width), the crossed dagger points stop at shoulder height, the boots stop well inside the inner ring, and the top of the head is at least one full head-height below the disc rim. Render the WHOLE disc, its outer ring band and the plate under the figure, at reference lightness, a hair lighter, never darker, evenly all round, with NO cast shadow and no ambient darkening of the disc from the creature."
retry('orc-master-assassin', 6, comp=COMP + FIT + COMPACT + BRIGHT + OMA_FIT,
      subject=next(a for a in A if a['id'] == 'orc-master-assassin')['subject'].replace('BARE-HEADED with shaved sides and a tall RED-BROWN TOPKNOT (no hood, no helmet)', 'BARE-HEADED with shaved sides and a short RED-BROWN PONYTAIL tied low behind the head (no hood, no helmet, no tall topknot)'))

# Pack 7: fire-imp v1 passed the numeric gate (base_drift -4.64, radius 0.8585) but its masked body luminance was 62.11 (< the 65 target) and it read as a dark red mass in the 48px grayscale sheet. Same design, brighter vermilion-orange skin with broad pale highlight planes and pale bone horns.
FI_BRIGHT = " Calibration from the previous generation of this exact token: the design was right, but the deep scarlet skin read as a DARK red mass at 48px, especially in grayscale. This time keep the same wiry imp with both arms raised throwing a fire ball overhead, small folded batwings and a curled tail with a flame tip, but paint the skin a BRIGHT VERMILION-ORANGE (lighter and more orange than before) with broad pale peach-orange highlight planes on every upper-left surface, translucent pale amber-orange batwings, and PALE BONE-GREY horns with cream tips instead of charcoal ones; only the eye slits, the mouth interior and thin seams stay dark. The disc stays exactly at reference lightness, a hair lighter, never darker."
retry('fire-imp', 7, comp=COMP + FIT + COMPACT + BRIGHT + FI_BRIGHT,
      subject=next(a for a in A if a['id'] == 'fire-imp')['subject'].replace('SCARLET-RED imp', 'BRIGHT VERMILION-ORANGE imp').replace('two curved CHARCOAL-DARK-GREY horns with pale tips', 'two curved PALE BONE-GREY horns with cream tips'))

# Pack 8: gaeramarth v1 passed the gate (base_drift -3.01, intrusion 8.44, radius 0.8585) but at 48px it is a pale radial spider almost identical to the shipped chitinous-spider (and near nimisil); the raised front legs were barely lifted. Same identity, a real rearing pose: the whole cephalothorax raised, four front legs held high in a V, abdomen low behind.
GA_REAR = " Calibration from the previous generation of this exact token: the colours and the ivory skull marking were right, but the spider lay flat with radial legs and looked like the shipped cream chitinous spider at small size. This time the gaeramarth REARS UP like a threatening tarantula seen from the front: the abdomen stays low at the back of the disc, the head and chest are lifted high in the middle, and the FOUR FRONT LEGS are held high and wide in a bold V above and beside the head with the hooked tips pointing up and outward, fangs bared, while the four hind legs are planted close and short under the body. The silhouette must read as a tall triangle with a V of raised legs, not as a flat round radial spider. Keep the ash-grey and bone-white colouring with charcoal-grey leg bands and the ivory skull marking on the abdomen, and add strong charcoal-grey and bone-white contrast bands on the legs so it does not look cream."
retry('gaeramarth', 8, comp=COMP + FIT + COMPACT + BRIGHT + GA_REAR,
      subject=next(a for a in A if a['id'] == 'gaeramarth')['subject'].replace('its TWO LONG FRONT LEGS REARED HIGH in the air in a threatening rush pose while the six other legs stay tucked close and bent around the body (the raised legs pulled well inside the disc)', 'its body REARED UP with the FOUR FRONT LEGS held high in a wide V in a threatening rush pose while the four hind legs stay planted close and short under the body (the raised legs pulled well inside the disc)'))
