-- Display geometry only. Never change the actor's size_category or combat data.
local M={}
-- Keep the native tactical meanings: green friend, blue neutral, red enemy.
M.colors={enemy={225,55,40},friend={72,210,105},neutral={65,125,245},player={30,195,245}}
-- Restore the 0.4.4 palette by user preference; keep the existing badge shapes.
-- These are native Actor:textRank colors, distinct from tactical frame hues.
M.rank_colors={rare={250,128,114},unique={244,164,96},boss={255,119,0},elite_boss={255,215,0},god={255,64,0}}
M.rank_color_order={'rare','unique','boss','elite_boss','god'}
M.relation_color_order={'friend','neutral','enemy'}
M.relation_color_defaults={friend=M.colors.friend,neutral=M.colors.neutral,enemy=M.colors.enemy}

local function validColor(c)
 if type(c)~='table' then return false end
 for i=1,3 do
  local v=c[i]
  if type(v)~='number' or v~=v or v<0 or v>255 or v~=math.floor(v) then return false end
 end
 return true
end

local function configuredColor(field,key,defaults)
 local settings=config and config.settings and config.settings.tome
 local palette=settings and settings[field]
 local color=type(palette)=='table' and palette[key]
 return validColor(color) and color or defaults[key]
end

function M.rankColor(badge)
 return configuredColor('checker_rank_colors',badge,M.rank_colors)
end

function M.relationColor(kind)
 if kind=='player' then return M.colors.player end
 return configuredColor('checker_relation_colors',kind,M.relation_color_defaults)
end

local function savePalette(palette,field,order)
 -- Serialize only known keys and validated RGB integers, never user text.
 local clean,lines={}, {'tome.'..field..' = {'}
 for _,key in ipairs(order) do
  local color=palette[key]
  if validColor(color) then
   clean[key]={color[1],color[2],color[3]}
   lines[#lines+1]=(' %s={%d,%d,%d},'):format(key,color[1],color[2],color[3])
  end
 end
 lines[#lines+1]='}\n'
 game:saveSettings('tome.'..field,table.concat(lines,'\n'))
 config.settings.tome[field]=clean
 if game.level and game.level.map then game.level.map:redisplay() end
end

local function setColor(key,color,field,order,defaults)
 if not defaults[key] or not validColor(color) then return false end
 local previous=config.settings.tome[field]
 local palette={}
 for _,name in ipairs(order) do
  palette[name]=type(previous)=='table' and previous[name] or nil
 end
 palette[key]=color
 savePalette(palette,field,order)
 return true
end

function M.setRankColor(badge,color)
 return setColor(badge,color,'checker_rank_colors',M.rank_color_order,M.rank_colors)
end

function M.setRelationColor(kind,color)
 return setColor(kind,color,'checker_relation_colors',M.relation_color_order,M.relation_color_defaults)
end

function M.resetRankColors()
 savePalette({},'checker_rank_colors',M.rank_color_order)
end

function M.resetColors()
 M.resetRankColors()
 savePalette({},'checker_relation_colors',M.relation_color_order)
end

-- The mechanical exporter centres each master's visible bounds and fits them
-- to this share of the square canvas. It must stay equal to target_occupancy
-- in tools/export_token.c: the faction ring is positioned from this constant,
-- so changing one side alone would detach the rim from the painted disc.
M.art_occupancy=.86
-- Painted disc diameter on screen, as a share of one map cell. Tokens no
-- longer draw a health or shield lane, so the flat piece grows to fill the
-- cell: a .92-cell disc inside a thin .035-cell faction ring, outer edge
-- .955 cell. At 48px that leaves a 1-2px gap between neighbours. The ring is
-- centred on the disc edge, so the ring lane is a diameter addition here and
-- the _relation-* masks in tools/prepare_runtime_art.py use the same
-- .955-cell canvas.
M.token_diameter=.92
M.ring_lane=.035

-- 1.25x layered small-tile trial. The decision to use the layered path (the
-- <=48px cell threshold and the id list) lives next to the single flag in
-- CheckerTokens.lua; this module only owns the drawing geometry. M.layer_scale
-- is the creature enlargement, measured against the same token canvas, so 1.0
-- would sit exactly where the flattened art sits.
M.layer_scale=1.25

function M.layerSize(cell,scale)
 return cell*(scale or 1)*M.layer_scale
end

-- Standee geometry. The own-cell board piece (shared disc, faction ring, rank
-- badge, native tactical life bar) keeps today's geometry; only the cut-out
-- creature is enlarged upward like a native display_h=2 / display_y=-1 tall
-- sprite. The height is per identity: M.standeeHeight reads the committed
-- native-tall table generated by tools/build_standee_heights.py, so a buff that
-- changes size_category can never flip a token mid-fight. Width is capped at
-- 1.0 cell like a native 64x128 tall sprite (which never spills sideways),
-- scaling stays uniform, and the feet sit at the disc centre plus
-- M.standee_feet * disc radius. A wide cut-out is therefore width-capped and
-- ends up shorter than its height cap. The canvas is per file (256px for
-- standee layers, 128px for ordinary R32 layers) and is passed in from the
-- geometry entry.
M.standee_width=1
M.standee_feet=0.55
-- Standees are drawn only at tiles >= 24px; below that (16px, small custom
-- sizes) the flat token is used.
M.standee_min_cell=24
-- Generated native-tall height table (id -> max height in cells). Loaded from
-- the committed data file; see tools/build_standee_heights.py. An id absent
-- here is not natively tall, and a value of exactly 1.0 means the native body
-- is <= 1.25 cells tall. M.standee_height_override is an optional per-identity
-- manual fix (id -> cells), empty until one id needs it; it wins.
M.standee_heights_path='/data-checker-revised/token-standee-heights.lua'
M.standee_heights={}
do
	-- Prefer the engine's virtual path; fall back to the file next to this module
	-- so the dofile/loadfile unit harnesses exercise the shipped table too
	-- (the same harness pattern CheckerTokens.loadStyle uses).
	local function loadHeights(path)
		if type(path)~='string' or type(loadfile)~='function' then return nil end
		if fs and fs.exists and not fs.exists(path) then return nil end
		local chunk=loadfile(path)
		if not chunk then return nil end
		local ok,data=pcall(chunk)
		if ok and type(data)=='table' then return data end
	end
	local heights=loadHeights(M.standee_heights_path)
	if not heights then
		local source=debug.getinfo(1,'S').source
		if type(source)=='string' and source:sub(1,1)=='@' then
			local dir=source:sub(2):match('^(.*[/\\])') or './'
			heights=loadHeights(dir..'../../../data/token-standee-heights.lua')
		end
	end
	M.standee_heights=heights or {}
end
-- Manual height review (R42/R43/R44/R46, user decision). Standee height counts
-- the BODY only: head, horns, helmets, hats, hair, raised ARMS, WINGS and FINS
-- are body; raised weapons, staves, floating orbs, debris, particles, flames,
-- lightning and glow are not. forge-giant's head flame is NOT body (user).
-- Sparse or semi-transparent fringes (bristles, specks, mist, shroud, warm
-- glow) are also not body. R46 reproducible measure: the body top is the FIRST
-- ROW with at least 6 pixels above alpha 128 (the "solid top", implemented as
-- tools/build_standee_heights.py:solid_top). weaver-queen, archmage-tarelion,
-- duathedlen, onilug and ninandra are read from that row; a reason that quotes
-- a y gives the solid-top (or, where noted, the alpha>128 top) it came from.
-- Energy/cloud/elemental beings whose glow, cloud or element IS the body keep
-- their derived cap (decision 3, R48 extension). The original three: greater-
-- telugoroth and ultimate-telugoroth (desc: blurred form) and daelach (desc:
-- cloud of fiery darkness). R48 adds: fyrk and ultimate-faeros (desc: fire
-- elementals), ultimate-teluvorta (desc: time elemental), maelstrom (desc:
-- vortex of ice and lightning), ultimate-gwelgoroth (desc: air elementals) and
-- glacial-legion (desc: shifting, ethereal form).
-- The generated cap measures the native 64x128 alpha bbox, so any non-body
-- part at the bbox top is cut down here to the standing-body height (cells).
-- tools/build_standee_heights.py --review lists every candidate and --solid
-- reports every id whose solid top differs from the effective cap by > 1/64;
-- the ids below were reviewed sprite by sprite and their cap is replaced. An id
-- whose head/horns/helmet/hair/arms/wings/fins are at the bbox top keeps the
-- derived cap and is not listed (thaurhereg, harkor-zun, spellblaze-simulacrum,
-- corrupted-sand-wyrm, rotting-titan, temporal-defiler,
-- prox and ogre-warmaster keep it for exactly that reason). A body-only cap of
-- 1.0 sends the id to the flat token: kra-tor's axe blade sits above a ~1-cell
-- body, boiling-horror's steam is a particle above the frothing ball and
-- archmage-tarelion's solid top is below 1.0 cells.
-- Each value is (bottom - head_top + 1)/64 - 0.25 for the head/horn top row,
-- clamped to [1.0, 1.75]; a reason that quotes a y gives the row its number
-- came from. Per-id reasoning and the full 151-id table:
-- docs/standee-body-review.md; the colour sweep for the ids that still use
-- their derived cap: tools/sweep_standee_tops.py and
-- evidence/token-standee-shape-20261004/README.md.
M.standee_height_override={
	-- Reviewed against the native sprite; the value is the body height in cells.
	['ak-gishil']=1.34375, -- floating swords above the head (head top y=25)
	['arch-zephyr']=1.21875, -- lightning arcs above the hood (hood top y=31)
	['archmage-tarelion']=1.0, -- warm glow rows 41-46 excluded; solid top y=49 -> 0.96875 clamped to 1.0 (flat)
	['argoniel']=1.0, -- raised sword and staff above the head; body ~1 cell
	['boiling-horror']=1.0, -- steam column is a particle; the frothing ball top is the body (flat)
	['blade-horror']=1.0, -- blades above the body
	['burb-snow-giant-champion']=1.53125, -- lightning above the dark horns (horn top y=13)
	['caldizar']=1.25, -- staff and motes above the raised hand/head
	['celia']=1.390625, -- staff above the head; the head top (y=23) is body
	['cryomancer']=1.0, -- staff and orb above the hood; body ~1 cell
	['duathedlen']=1.265625, -- darkness shroud excluded; solid head top y=31
	['elandar']=1.0, -- staff and orb above the head; body ~1 cell
	['emperor-wight']=1.0, -- raised sword above the crown; body ~1 cell
	['fallen-sun-paladin-aeryn']=1.0, -- raised long sword above the head
	['fillarel-aldaren']=1.0, -- staff and orb held above the head; body ~1 cell
	['forge-giant']=1.328125, -- head flame is not body (head top y=27)
	['geomancer']=1.0, -- staff and orb held above the hat; body ~1 cell
	['gigantic-gravity-worm']=1.40625, -- lightning above the head (head top y=21)
	['gigantic-sandworm-tunneler']=1.40625, -- lightning above the head (head top y=21)
	['greater-teluvorta']=1.0, -- floating spell orb above the body
	['half-finished-bone-giant']=1.21875, -- purple halo rows 31-33 (max alpha 18/62/115, none >128) is not body; skull/head solid top y=34
	['heavy-sentinel']=1.546875, -- orange glow above the skull (skull top y=13)
	['high-sun-paladin-aeryn']=1.0, -- raised long sword above the head
	['khulmanar']=1.09375, -- club slung above the shoulder
	['kra-tor']=1.0, -- axe blade above the head; the body is ~1 cell (flat)
	['kryl-feijan']=1.0, -- scattered darkness cloud rows 3-55 is not body; first non-darkness body row (blue claw-like limbs) y=58 -> 0.84375 clamped to 1.0 (flat)
	['kyless']=1.0, -- staff and orb held above the head; body ~1 cell
	['lady-nashva']=1.234375, -- trident above the head
	['lady-zoisla']=1.3125, -- trident and staff above the head
	['naga-nereid']=1.0, -- trident above the head; body ~1 cell
	['naga-tidecaller']=1.078125, -- trident above the head; the head top is body
	['naga-tidewarden']=1.0, -- trident above the head; body ~1 cell
	['ninandra']=1.140625, -- cool white/cyan (207,251,255) glow rows 30-37 above the head; alpha>128 top y=38; solid top y=39 is 1/64 lower
	['norgos-frozen']=1.359375, -- ice mist above the bear ears
	['ogre-guard']=1.078125, -- hammer and a floating speck above the head (head top y=43)
	['ogre-rune-spinner']=1.296875, -- raised arms are body; the vortex is excluded
	['ogric-abomination']=1.140625, -- club raised above the head
	['onilug']=1.015625, -- shadow excluded; solid head top y=47
	['pale-drake']=1.0, -- staff above the head; body ~1 cell
	['shiaak-venomblade']=1.0, -- raised blades above the body
	['snow-giant-boulder-thrower']=1.484375, -- boulder above the raised arms (arm top y=15)
	['snow-giant-thunderer']=1.40625, -- lightning above the head (head top y=20)
	['tempest']=1.0, -- staff and orb held above the head; body ~1 cell
	['urkis']=1.0, -- lightning above the head; body ~1 cell
	['uruivellas']=1.296875, -- fiery aura above the horns (horn top y=29)
	['void-spectre']=1.125, -- trailing wisp above the body
	['weaver-queen']=1.234375, -- sparse bristles/specks excluded; solid body top y=33
	['xhaiak-arachnomancer']=1.4375, -- smoke above the raised legs/arms (limb top y=20)
	['yeek-mindslayer']=1.0, -- raised psi-blade above the body
}

-- Height cap in cells for one identity, read statically from the committed
-- native-tall table (never from the live actor). nil means the id is not
-- natively tall and keeps the flat token; 1.0 is the flat marker.
function M.standeeHeight(id)
	local override=id and M.standee_height_override[id]
	if type(override)=='number' then return override end
	return id and M.standee_heights[id] or nil
end

-- Standees only at tiles >= M.standee_min_cell pixels.
function M.standeeCellAllowed(cell)
	local n=tonumber(cell)
	return n~=nil and n>=M.standee_min_cell
end

-- Pure standee geometry. box is the creature alpha bbox on the layer canvas
-- {"left","top","right","bottom",...} with right/bottom exclusive, measured by
-- tools/build_token_layers.py. canvas is that file's square size in px (the
-- geometry entry's canvas field; 256 for standee layers). box.body_top is the
-- y of the top of the BODY (head, horns, helmet, hair, raised arms and wings
-- count; raised weapons, staves, orbs and particles do not); it defaults to the
-- alpha top when the geometry has no reviewed value. height is the height cap
-- in cells from M.standeeHeight. Feet-to-body_top is scaled to the cap, so a
-- raised weapon above body_top may stick out above; the whole art is still
-- capped at M.standee_width cells wide, and the uniform scale shrinks when that
-- cap binds. Returns the screen quad (left,top,size) that draws the whole
-- canvas at one uniform scale, or nil when box or height is invalid.
function M.standeeQuad(cell,box,canvas,disc_cx,disc_cy,disc_d,height)
	if type(box)~='table' then return nil end
	local left,top,right,bottom=box.left,box.top,box.right,box.bottom
	if type(left)~='number' or type(top)~='number' or type(right)~='number' or type(bottom)~='number' then return nil end
	local bw,bh=right-left,bottom-top
	if bw<=0 or bh<=0 then return nil end
	local cap=tonumber(height)
	if not cap then return nil end
	local body_top=tonumber(box.body_top) or top
	local body_h=bottom-body_top
	if body_h<=0 then return nil end
	local scale=math.min(cap*cell/body_h,M.standee_width*cell/bw)
	local size=(canvas or 128)*scale
	return disc_cx-((left+right)/2)*scale,(disc_cy+M.standee_feet*disc_d/2)-bottom*scale,size
end

-- Native shader-aura geometry for a standee, in map-cell units relative to the
-- actor's own cell origin (exactly how the engine chains add_mos on the
-- display Entity). The native aura is built from selfbase.image -- for a token
-- that is the flat disc -- at a fixed display_h=2 / display_y=-1 box, so it hugs
-- the own cell instead of wrapping the upright figure. For a standee the aura
-- must use the standee layer image at the standee quad instead. Deriving the
-- cell-unit box here keeps it identical to M.standeeQuad at any tile size:
--   screen box = (cell*dx, cell*dy, cell*w, cell*h).
-- R46: the aura texture can be non-square (128x256 for a tall body). The quad
-- aspect must equal the texture aspect, so canvas_w/canvas_h are separate and
-- the function returns display_x, display_y, display_w, display_h or nil. The
-- factor is unchanged (cells per aura-texture pixel).
function M.standeeAuraQuad(box,canvas_w,canvas_h,height)
	if type(box)~='table' then return nil end
	local left,top,right,bottom=box.left,box.top,box.right,box.bottom
	if type(left)~='number' or type(top)~='number' or type(right)~='number' or type(bottom)~='number' then return nil end
	local bw,bh=right-left,bottom-top
	if bw<=0 or bh<=0 then return nil end
	local cap=tonumber(height)
	if not cap then return nil end
	local cw,ch=tonumber(canvas_w),tonumber(canvas_h)
	if not cw or cw<=0 or not ch or ch<=0 then return nil end
	-- Body-only height, exactly like M.standeeQuad, so the aura follows the
	-- creature quad after the body_top change. The aura box records its own
	-- body_top (the layer body_top mapped onto the aura canvas).
	local body_top=tonumber(box.body_top) or top
	local body_h=bottom-body_top
	if body_h<=0 then return nil end
	-- cells of screen per aura-texture pixel; isotropic, so one factor for both
	-- axes and the quad aspect matches canvas_w:canvas_h.
	local factor=math.min(cap/body_h,M.standee_width/bw)
	local w,h=cw*factor,ch*factor
	if w<=0 or h<=0 then return nil end
	return .5-((left+right)/2)*factor,
	 .5+M.standee_feet*M.token_diameter/2-bottom*factor,
	 w,h
end

function M.scale(size,tile)
 -- One board piece, one diameter. size_category and tile size describe the
 -- creature and the viewport, not the playing piece: tiering them made
 -- neighbouring tokens differ by 7px at 64px cells and read as misaligned.
 -- The arguments are kept so existing call sites stay unchanged.
 return M.token_diameter/M.art_occupancy
end

function M.relation(actor,viewer,reaction)
 return actor==viewer and 'player' or reaction<0 and 'enemy' or reaction>0 and 'friend' or 'neutral'
end

function M.geometry(x,y,cell,scale)
 -- AI artwork occupies M.art_occupancy of its square. The faction ring lane
 -- sits outside it; M.ring_lane is the whole diameter addition so the mask
 -- canvas is exactly the outer edge of the ring.
 local diameter=cell*(M.art_occupancy*scale+M.ring_lane)
 return {x=x+(cell-diameter)/2,y=y+(cell-diameter)/2,d=diameter,
  cx=x+cell/2,cy=y+cell/2,cell=cell}
end

-- Native tactical life bar, reproduced instead of copied from the engine so a
-- board token shows exactly what the game draws when tokens are off. All
-- geometry, thresholds, RGB and alphas cite game/modules/tome/class/Actor.lua:
--   mode choice   : 1303-1308 (small frame only with view_faction + always_target~='old')
--   small side    : 1017-1036 (friend left / enemy right, dy stacked from the bottom)
--   small bottom  : 1104-1121 (dx grows left to right)
--   big side      : 1198-1214 (literal 3px inset)
--   big bottom    : 1215-1229 (literal 3px inset)
-- tests/native_lifebar.lua parses that file and asserts these numbers, so this
-- table cannot silently drift away from the engine.
M.native_life_bar={
 small_bottom={sx=.078125,dx=.90625,sy=.9375,dy=.984375},
 small_side={sx=.015625,dx=.0625,sy=.03125,dy=.953125,enemy_sx=.9375},
 big={inset=3,side_dw=.1,bottom_dh=.1},
 bands={
  {min=.75,track={129,180,57},fill={50,220,77}},
  {min=.5,track={175,175,10},fill={240,252,35}},
  {min=.25,track={185,88,0},fill={255,156,21}},
  {min=-math.huge,track={167,55,39},fill={235,0,0}},
 },
 track_alpha=128,fill_alpha=255,epsilon=.0001,
}

-- Native fraction: math.max(0,life)/max_life + 0.0001 (Actor.lua band lines).
function M.nativeLifeFraction(actor)
 local max=actor.max_life or 0
 if max<=0 then return 0 end
 return math.max(0,actor.life or 0)/max+M.native_life_bar.epsilon
end

-- Choose the exact native bar variant. nil means the engine draws no bar:
-- with no game.always_target the border alone is drawn, never a bar.
function M.nativeBarMode(map)
 if not (map and game and game.always_target) then return nil end
 local side=config and config.settings and config.settings.tome and config.settings.tome.small_frame_side
 -- Native: small frame only with view_faction + always_target~='old'; every
 -- other truthy always_target uses the big frame (whose bar does not need
 -- view_faction). No always_target means the border alone, never a bar.
 if map.view_faction and game.always_target~='old' then return side and 'small-side' or 'small-bottom' end
 return side and 'big-side' or 'big-bottom'
end

-- Draw only the native tactical life bar (no native border tiles): the board
-- token's thin faction ring replaces those. mode is one of small-bottom,
-- small-side, big-bottom, big-side; side_enemy only moves the small side bar.
function M.nativeLifeBar(actor,x,y,w,h,mode,side_enemy)
 local b=M.native_life_bar
 local lp=M.nativeLifeFraction(actor)
 local band=b.bands[#b.bands]
 for _,candidate in ipairs(b.bands) do if lp>candidate.min then band=candidate break end end
 local function quad(qx,qy,qw,qh,c,a) core.display.drawQuad(qx,qy,qw,qh,c[1],c[2],c[3],a) end
 if mode=='small-bottom' then
  local g=b.small_bottom
  local sx,dx,sy,dy=w*g.sx,w*g.dx-w*g.sx,h*g.sy,h*g.dy-h*g.sy
  quad(x+sx,y+sy,dx,dy,band.track,b.track_alpha)
  quad(x+sx,y+sy,dx*lp,dy,band.fill,b.fill_alpha)
 elseif mode=='small-side' then
  local g=b.small_side
  local sx=side_enemy and w*g.enemy_sx or w*g.sx
  local dx,sy,dy=w*g.dx-w*g.sx,h*g.sy,h*g.dy-h*g.sy
  quad(x+sx,y+sy,dx,dy,band.track,b.track_alpha)
  quad(x+sx,y+sy+dy*(1-lp),dx,dy*lp,band.fill,b.fill_alpha)
 elseif mode=='big-side' then
  local dw,inset=w*b.big.side_dw,b.big.inset
  quad(x+inset,y+inset,dw,h-2*inset,band.track,b.track_alpha)
  quad(x+inset,y+inset+(h-2*inset)*(1-lp),dw,(h-2*inset)*lp,band.fill,b.fill_alpha)
 elseif mode=='big-bottom' then
  local dh,inset=h*b.big.bottom_dh,b.big.inset
  quad(x+inset,y+h-dh,w-2*inset,dh,band.track,b.track_alpha)
  quad(x+inset,y+h-dh,(w-2*inset)*lp,dh,band.fill,b.fill_alpha)
 end
end

-- Rank badge size in px for one map cell. Above 16px this keeps the historic
-- 12x9 floor and proportional size. At <=16px that floor covered most of a
-- 16px token, so the badge is scaled to the cell instead (6x5 at 16px).
function M.badgeSize(cell)
 local n=tonumber(cell) or 0
 if n<=16 then
  return math.max(4,math.floor(n*.38+.5)),math.max(3,math.floor(n*.30+.5))
 end
 return math.max(12,n*.23),math.max(9,n*.18)
end

function M.rankBadge(rank)
 -- Critter (1), normal (2) and elite (3) intentionally share an unmarked base.
 -- Elite boss (5) is a separate native rank and retains its crown.
 if rank==3.2 then return 'rare' end
 if rank==3.5 then return 'unique' end
 if rank==4 then return 'boss' end
 if rank==5 then return 'elite_boss' end
 if rank==10 then return 'god' end
end

return M
