# Retries (pack 6): greater faeros v1 drew flame plumes past the disc edge (radius 0.874, limit 0.867, intrusion 21.0),
# and its brief made it a broad burly flame giant, which is what the shipped-to-be Fyrk already is.
FIT = " Calibration from the previous generation of this exact token: it drew flame plumes and the crest reaching past the edge of the disc, so the token could not be exported. This time draw the figure markedly smaller and tighter: the ENTIRE figure, every flame lick included, fits inside a circle of about two thirds of the disc radius around the disc centre, leaving a wide bare charcoal ring of base plate on every side."
FYRK_REF = ('family', 'game/addons/tome-checker-revised/art/production/handoffs/monster-batch-m-3/fyrk/imagegen-calls/call-1/export-128.png',
            'Fyrk token already made (broad hulking crimson-scarlet flame guardian, heavy shoulders): the greater faeros must NOT resemble it; it is a taller, lighter, more upright golden-orange figure with a single tall plume and a trailing flame mantle.')
retry('greater-faeros', 6, comp=COMP + FIT,
      refs=[STY, IDN('elemental_fire_greater_faeros.png', 'Native shape: a burly flame figure with a tall flame crest and long hanging claws.'), FYRK_REF],
      subject="A greater fire elemental seen from a steep overhead three-quarter angle, drawn compact: an upright, tall-standing humanoid of flame in bright golden-orange and yellow with a white-yellow core, a moderately wide chest, both long arms held forward at mid height with open clawed hands of flame, a single tall narrow plume of flame rising from the head, an incandescent white-yellow face with two dark ember eyes, and a long flowing mantle of flame streaming behind and beside the shoulders. Taller and lighter than a hulking brute. Blazing and complete.",
      contrast="Fire elementals: the plain faeros is a lean X-shaped figure with arms flung wide in bright orange; the greater faeros is the UPRIGHT golden-orange one with arms forward, one tall head plume and a flame mantle (silhouette: single vertical plume, forward claws, trailing mantle; hue: golden-yellow-orange; value: light). Fyrk is a hulking heavy-shouldered crimson-scarlet guardian; do not draw a broad burly body or a crimson tone.")
