// Read-only decoded-image audit in Chromium; never changes source pixels.
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),config=JSON.parse(fs.readFileSync(path.join(__dirname,'capture-config.json')));
const {chromium}=require(config.playwright);
(async()=>{const browser=await chromium.launch({executablePath:config.browser,headless:true,args:['--no-sandbox','--disable-gpu','--allow-file-access-from-files']});try{
 const page=await browser.newPage();await page.goto('file://'+path.join(__dirname,'index.html'));
 const files=['up','down','world'].flatMap(id=>['masters/stairs-'+id+'-v1.png',...[48,64,96,128,256].map(s=>'sprites/'+s+'/stairs-'+id+'.png')]);
 const results=[];for(const file of files){const result=await page.evaluate(async url=>{const i=new Image();i.src=url;await i.decode();const c=document.createElement('canvas');c.width=i.naturalWidth;c.height=i.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(i,0,0);const p=ctx.getImageData(0,0,c.width,c.height).data;let transparent=0,partial=0,opaque=0,nearOpaque=0,borderNonzero=0,borderMaxAlpha=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const a=p[(y*c.width+x)*4+3];if(a===0)transparent++;else if(a===255)opaque++;else partial++;if(a>=248)nearOpaque++;if((x===0||y===0||x===c.width-1||y===c.height-1)&&a){borderNonzero++;borderMaxAlpha=Math.max(borderMaxAlpha,a);}}return{width:c.width,height:c.height,transparent,partial,opaque,nearOpaque,borderNonzero,borderMaxAlpha,centerAlpha:p[(Math.floor(c.height/2)*c.width+Math.floor(c.width/2))*4+3]};},'file://'+path.join(root,file));if(!result.transparent||!result.nearOpaque||result.centerAlpha<248||result.borderMaxAlpha>8)throw Error('Alpha or visible-margin failure: '+file);results.push({file,...result});}
 fs.writeFileSync(path.join(__dirname,'alpha-validation.json'),JSON.stringify({method:'Read-only Chromium canvas RGBA decode',passed:true,acceptance:'Native transparent exterior, center alpha >=248, near-opaque subject pixels >=248, border alpha <=8 (same visible-bounds threshold as C exporter). Original alpha retained, never clamped.',files:results},null,2)+'\n');console.log('PASS: '+results.length+' masters/exports have native transparent pixels, near-opaque subjects and no visible outer-edge alpha above 8/255.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
