# Retry packs are appended here (never edited in place).

# Pack 5: elven-corruptor v1 failed only the disc-overflow gate (max opaque radius 0.877 > 0.867; base_drift -6.68 and intrusion passed): the tall bone-topped staff at the upper left and the orbiting shards at the upper right crossed the disc rim. Same design, SHORT staff, shards pulled tight, figure smaller and centred.
EC_FIT = " Calibration from the previous generation of this exact token: the design, the orchid-magenta and plum robes and the silver-haired elf were right, but the tall staff and the orbiting bone shards stuck OUT across the disc rim. This time keep the same elf, robes and colours, but hold a SHORT bone-topped staff (no longer than the elf's shoulder height, held close to the body, its head well below the elf's head height) and draw the three bone shards tiny and hugging the body just outside the shoulders. Put the figure exactly in the centre of the disc with the WHOLE figure, staff and shards included, inside a circle of about two thirds of the disc radius and a wide bare ring of plate on every side, nothing touching or crossing the disc rim. Render the WHOLE disc, its outer ring band and the plate under the figure, at reference lightness, a hair lighter, never darker, evenly all round, with NO cast shadow and no ambient darkening of the disc."
retry('elven-corruptor', 5, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + EC_FIT,
      subject=next(a for a in A if a['id'] == 'elven-corruptor')['subject'].replace('holding a BONE-TOPPED STAFF in the right hand angled up and outward (the staff head a small bone skull-crescent, the staff short enough to stay inside the disc)', 'holding a SHORT BONE-TOPPED STAFF close to the body in the right hand (the staff head a small bone skull-crescent, the staff no taller than the shoulder)').replace('THREE small pale BONE SHARDS orbiting the body at shoulder height', 'THREE tiny pale BONE SHARDS hugging the body just outside the shoulders'))

# Pack 6: orc-fighter v1 failed only the base_drift gate (median -10.36, tolerance +-8; radius and intrusion passed): the plate around the heavy armour came out DARKER than the reference (cast shadow of the big shield and axe). Same design, figure a little smaller, no cast shadow, disc at exactly reference lightness.
OF_FIT = " Calibration from the previous generation of this exact token: the design, the gunmetal plate, the big shield and the low waraxe were right, but the plate around the armour came out DARKER than the style reference (the shield and axe cast a dark shadow onto the disc). This time keep the same orc fighter, but draw it a little SMALLER (the whole figure inside a circle of about two thirds of the disc radius, centred, with a wide bare ring of plate on every side) with NO cast shadow, NO contact shadow and NO dark halo under or around the shield, axe or feet. Render the WHOLE disc, its outer ring band and the plate under and around the figure, at exactly the reference lightness or a hair lighter, evenly all round, warm-neutral mid charcoal, with no ambient darkening of the disc from the armour."
retry('orc-fighter', 6, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + OF_FIT)

# ---- Refinement packs (coordinator review of batch X): skeleton-assassin v1 and assassin v1 passed every numeric gate (masked luminance 62.7 each) and are catalogued, but the 48px review found that both lose their silhouette on every floor (thin figure, dark slate cowl / dark straps and sash). Both are re-rolled through the declared refinement path; v1 stays as SUPERSEDED evidence.
def _pin(rel):
    return {'path': rel, 'sha256': sha(rel)}


_AD = 'game/addons/tome-checker-revised/art/production/handoffs/monster-batch-x-3/'
_MX = 'game/addons/tome-checker-revised/art/monster-batch-x/'
SA_LIGHT = " LIGHT-VALUE REFINEMENT (the previous version was rejected at 48 pixels: a thin lean figure with a dark slate cowl and dark straps lost its silhouette on every floor): draw the skeleton as a BONE-WHITE and IVORY skeleton (very light, only soft warm-grey shadow planes) wrapped in a LARGE, broad, tattered pale ash-grey and light periwinkle-grey cloak and hood covering much of the body (the cloak clearly lighter than the copper-grey disc bevel, with bright pale frayed edge strips), thin pale-tan straps, two bright polished steel daggers, small orange-red eye glints, and a bright pale RIM LIGHT along the whole outline. The figure is compact and BIG: it fills the inner three quarters of the disc (about 0.7 of the disc radius across, centred, daggers tucked inside), NOT thin. No black, charcoal or dark-blue mass anywhere; NO cast shadow, contact shadow or dark halo on the plate; render the whole disc, outer ring and plate under the figure at exactly the reference lightness, a hair lighter, never darker."
retry('skeleton-assassin', 7, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + SA_LIGHT,
      subject="A skeleton assassin seen from a steep overhead three-quarter angle: a compact crouched hooded skeleton, the bones BONE-WHITE and IVORY with bright cream highlight planes on the skull, ribs and joints, wrapped in a broad tattered LIGHT ASH-GREY and pale PERIWINKLE-BLUE cloak and hood with bright frayed pale edge strips, a thin pale-tan bandolier, TWO BRIGHT POLISHED STEEL DAGGERS held low in reverse grip (short, inside the disc), small hot ORANGE-RED eye glints in the hood shadow, knees bent, leaning forward towards the upper left. Stealthy, angular, bone-and-cloak, bright and complete.",
      refinement={'supersedes': 'skeleton-assassin', 'previous_batch': 'monster-batch-x-3',
                  'design_change_reason': "The first skeleton assassin (charred ash-grey bones, dark slate-blue cowl, dark straps; masked luminance 62.7) passed the numeric style gate but the coordinator's 48px floor review found the thin figure lost its silhouette on every floor. This refinement changes the value design, not just the roll: ivory bone-white skeleton, a broad light ash-grey and periwinkle cloak instead of a dark cowl, pale straps, bright steel, and a larger compact figure so the body mass is light.",
                  'evidence': [_pin(_MX + 'masters/skeleton-assassin-v1.png'), _pin(_AD + 'skeleton-assassin/imagegen-calls/call-1/call.json'), _pin(_AD + 'skeleton-assassin/receipts/attempt-1.json')]})

AS_LIGHT = " LIGHT-VALUE REFINEMENT (the previous version was rejected at 48 pixels: dark brown leather straps, a dark wine sash, dark boots and thin limbs lost the silhouette on every floor): draw the assassin in a LIGHT SLATE and GREY-BLUE cloak and hood (a broad cloak flaring behind the lunge, clearly lighter than the copper-grey disc bevel, with a BRIGHT pale rim light along the whole outline), a pale dove-grey tunic and trousers, light tan-grey leather straps, gloves and boots (no dark brown, no black), a brighter rose-red sash, and a BRIGHT POLISHED STEEL HIGHLIGHT along both dagger blades. The figure is compact and BIG: it fills the inner three quarters of the disc (about 0.7 of the disc radius across, centred, blade tips inside), NOT thin. No black, charcoal or dark mass anywhere; NO cast shadow, contact shadow or dark halo on the plate; render the whole disc, outer ring and plate under the figure at exactly the reference lightness, a hair lighter, never darker."
retry('assassin', 8, comp=COMP + FIT + COMPACT + BRIGHT + DARKFIX + AS_LIGHT,
      subject="An assassin seen from a steep overhead three-quarter angle: a lean masked human LUNGING FORWARD towards the upper right on a bent front leg, wearing a broad flaring LIGHT SLATE and GREY-BLUE cloak with a deep hood and face mask leaving only a narrow eye slit with pale eyes, a pale dove-grey tunic and trousers, light tan-grey straps, bracers, gloves and boots, a ROSE-RED sash at the waist with a short tail, the RIGHT ARM stretched out ahead holding ONE LONG BRIGHT POLISHED STEEL DAGGER (bright edge highlight, blade inside the disc) and the left hand low behind holding a second short steel dagger. Swift, masked, light-cloaked and complete.",
      refinement={'supersedes': 'assassin', 'previous_batch': 'monster-batch-x-3',
                  'design_change_reason': "The first assassin (dove-grey tunic but dark brown straps, dark wine sash, dark boots; masked luminance 62.7) passed the numeric style gate but the coordinator's 48px floor review found the thin figure lost its silhouette on every floor. This refinement changes the value design: a broad light slate and grey-blue flaring cloak with a bright rim, pale tan-grey leather instead of dark brown, a brighter sash, steel-highlighted blades, and a larger compact figure so the body mass is light.",
                  'evidence': [_pin(_MX + 'masters/assassin-v1.png'), _pin(_AD + 'assassin/imagegen-calls/call-1/call.json'), _pin(_AD + 'assassin/receipts/attempt-1.json')]})
