# Retry packs are appended here (never edited in place).

# Pack 5: dredge v1 failed only the base_drift gate (median -8.42, tolerance +-8; radius 0.8585 and intrusion 5.77 passed, no other blocking item): the brute was drawn far too large, fists and forearms reaching the outer ring band, and the plate around it came out darker than the reference. Same design, smaller figure folded in close, disc at reference lightness with no cast shadow.
DR_FIT = " Calibration from the previous generation of this exact token: the design and the colours were right, but the brute was drawn far too large: the fists and forearms reached the outer ring band and the plate under and around it came out DARKER than the reference. This time keep the same hunched salmon-pink stitched knuckle-walking brute with two enormously thick arms, heavy round fists and a tiny head, but draw it SMALLER: the whole figure, fists included, fits inside a circle of about two thirds of the disc radius with a wide bare ring of plate all round, the arms shorter and folded in closer to the body, the fists planted just in front of the chest. Render the WHOLE disc, its outer ring band and the plate under and around the figure, at reference lightness, a hair lighter, never darker, evenly all round, with NO cast shadow, no dark contact shadow and no ambient darkening of the disc from the creature."
retry('dredge', 5, comp=COMP + FIT + COMPACT + BRIGHT + DR_FIT)

# Pack 6: orc-pyromancer v1 failed the gate (max opaque radius 0.9645 > 0.867; base_drift -1.47 passed): the flaming staff head stuck out across the disc rim at the upper left and the export was shrunk around it. Same design, staff shorter and held close, everything inside the inner three quarters.
PY_FIT = " Calibration from the previous generation of this exact token: the design was right, but the long wooden staff with the fire ball stuck OUT of the disc across the rim at the upper left and the figure was placed off-centre. This time keep the same bald red-striped olive-green orc in a bright orange-red gold-trimmed robe with a yellow sash, but hold a SHORT staff (no longer than the orc's torso) angled up and outward at about forty degrees with the small orange fire ball on its head at shoulder height, both the staff head and the fire ball at least one full head-height inside the disc rim, the left hand open at the hip with a few tiny flames, and centre the whole figure in the disc with a wide bare ring of plate on every side. Render the WHOLE disc, its outer ring band and the plate under the figure, at reference lightness, a hair lighter, never darker, evenly all round, with NO cast shadow and no ambient darkening of the disc from the creature, and no glow from the fire on the plate."
retry('orc-pyromancer', 6, comp=COMP + FIT + COMPACT + BRIGHT + PY_FIT,
      subject=next(a for a in A if a['id'] == 'orc-pyromancer')['subject'].replace('the RIGHT ARM holding a wooden staff diagonally up and outward', 'the RIGHT ARM holding a SHORT wooden staff angled up and outward').replace('(the fire ball no bigger than the head and the staff tip well inside the disc)', '(the fire ball no bigger than the head, staff and fire ball well inside the disc)'))

# Pack 7: orc-cryomancer v1 produced no recorded output (codex reported an empty image path, provenance rejected; the call still counts). Same brief, unchanged apart from a calibration line.
CR_FIT = " Calibration: return the finished image and its file path. Keep the design exactly as briefed and the whole figure, arms and ice shards included, inside the inner three quarters of the disc. Render the WHOLE disc, its outer ring band and the plate under the figure, at reference lightness, a hair lighter, never darker, evenly all round, with NO cast shadow and no ambient darkening of the disc from the creature, and no frost glow on the plate."
retry('orc-cryomancer', 7, comp=COMP + FIT + COMPACT + BRIGHT + CR_FIT)

# Pack 8: bloated-horror v1 failed only the base_drift gate (median -8.76, tolerance +-8; radius 0.8585 and intrusion 5.91 passed): the big pale body and reaching hands filled the disc and the plate around them came out darker than the reference. Same design, smaller, arms drawn in, disc at reference lightness.
BH_FIT = " Calibration from the previous generation of this exact token: the design and colours were right, but the pale bloated body was drawn too large, the hands reached out towards the ring band and the plate around it came out DARKER than the reference. This time keep the same floating cream-white pear-shaped body with red-pink sores, purple veins and the large bald childlike head with round pale eyes and an open mouth, but draw it SMALLER: the whole figure fits inside a circle of about two thirds of the disc radius with a wide bare ring of plate all round, the two small arms held close against the chest instead of reaching out. Render the WHOLE disc, its outer ring band and the plate under and around the figure, at reference lightness, a hair lighter, never darker, evenly all round, with NO cast shadow, no dark contact shadow and no ambient darkening of the disc from the creature."
retry('bloated-horror', 8, comp=COMP + FIT + COMPACT + BRIGHT + BH_FIT,
      subject=next(a for a in A if a['id'] == 'bloated-horror')['subject'].replace('two SMALL stubby arms raised in front of the chest', 'two SMALL stubby arms held close against the chest'))

# Pack 9: orc-cryomancer v2 (pack 7) failed the base_drift gate (median +8.21, tolerance +-8, intrusion 14.08, radius 0.8585): the ice shards and hands spread out to the rim, the figure sat off-centre, and the disc around the pale frost came out LIGHTER than the reference. Same design, arms and shards drawn in close, centred, disc at reference lightness with no frost glow.
CR2_FIT = " Calibration from the previous generation of this exact token: the design was right, but the outstretched hands and the ice shards reached the outer ring band and even the disc rim on both sides, the figure was off-centre, and the plate around the pale frost came out LIGHTER than the reference. This time keep the same bare-headed olive-green orc with a white braid over the shoulder in an ice-blue rune-embroidered robe with a white sash, arms spread but SHORT and bent at the elbows (hands at shoulder width, not stretched out), with a small fan of only FOUR short pale-cyan ice shards close in front of the two hands, the whole figure including every shard inside a circle of about two thirds of the disc radius and centred in the disc with a wide bare ring of plate on every side. Render the WHOLE disc, its outer ring band and the plate under the figure, at exactly the reference lightness, neither lighter nor darker, evenly all round, with NO frost glow, no bright halo, no cast shadow and no ambient change of the disc from the creature or the ice."
retry('orc-cryomancer', 9, comp=COMP + FIT + COMPACT + BRIGHT + CR2_FIT,
      subject=next(a for a in A if a['id'] == 'orc-cryomancer')['subject'].replace('BOTH ARMS SPREAD WIDE to the sides with the palms pushed outward, and in front of and beside the hands a fan of SIX pale-cyan and white ICE SHARDS radiating outward (each shard short and the whole fan kept inside the inner three quarters of the disc)', 'BOTH ARMS bent and held out to the sides at shoulder width with the palms pushed outward, and close in front of the hands a small fan of FOUR short pale-cyan and white ICE SHARDS (the whole fan kept inside two thirds of the disc radius)'))

# Pack 10: drem-master v1 passed the numeric gate (base_drift -3.20, radius 0.8596) and its masked lum was 74.9, but the coordinator's 48px review rejected it: dark steel-grey mail on the dark disc loses the silhouette on every floor. Same design, clearly lighter value range (pale polished steel and bone-white cloth, strong light rim along the whole silhouette), slightly smaller figure.
DM_LIGHT = " Calibration from the previous generation of this exact token: the design and pose were right, but the dark grey-blue mail read as a DARK mass against the dark disc at very small size and the fist reached near the rim. This time keep the same stocky faceless stitched-mouth commander with one fist raised in command and a chipped waraxe pointing down, but paint the armour in a clearly LIGHTER value range: PALE POLISHED STEEL plates with broad near-white highlight planes on every upper-left surface, BONE-WHITE ragged cloth sash and tabard, a pale bone-grey head, bright ORANGE rust patches kept as small accents, and a STRONG LIGHT RIM (bright silver-white edge light) along the entire outline of the figure, so it reads as a light shape on the dark disc; only the mail links and joint seams stay mid-grey. Draw the figure a little SMALLER: the whole figure, raised fist and axe included, inside a circle of about two thirds of the disc radius with a wide bare ring of plate all round. Render the WHOLE disc, its outer ring band and the plate under the figure, at reference lightness, a hair lighter, never darker, evenly all round, with NO cast shadow and no ambient darkening of the disc from the creature."
retry('drem-master', 10, comp=COMP + FIT + COMPACT + BRIGHT + DM_LIGHT,
      subject=next(a for a in A if a['id'] == 'drem-master')['subject'].replace('DENTED STEEL-BLUE-GREY mail armour', 'DENTED but PALE POLISHED STEEL mail armour').replace('a ragged pale grey cloth sash', 'a ragged BONE-WHITE cloth sash and tabard').replace('PALE GREY faceless head', 'PALE BONE-GREY faceless head'))

# Pack 11: drem-master v2 (pack 10) had the right light figure (pale polished steel, bone-white cloth) but failed base_drift -8.45 (all eight sectors darker than the frozen baseline, radius 0.8599 passed): the whole disc plate came out darker than the reference. Same figure, disc explicitly brighter.
DM_DISC = " Calibration from the previous generation of this exact token: the figure was exactly right (pale polished steel armour with near-white highlights, bone-white ragged cloth, pale bone-grey stitched head, one fist raised, chipped axe pointing down, orange rust accents, light rim, about two thirds of the disc radius) and must be kept unchanged, but the DISC PLATE came out clearly DARKER than the style reference all the way round, including the outer ring band. This time render the entire disc plate, the flat charcoal-brown plate under and around the figure and the whole outer ring band with its copper-grey bevel, VISIBLY LIGHTER than in the previous attempt: match the style reference's plate brightness exactly, erring a little lighter, evenly all round, warm-neutral mid charcoal (not near-black), with NO cast shadow, no contact shadow, no vignette and no ambient darkening under or around the figure."
retry('drem-master', 11, comp=COMP + FIT + COMPACT + BRIGHT + DM_LIGHT + DM_DISC,
      subject=next(a for a in A if a['id'] == 'drem-master' and a['pack'] == 10)['subject'])
