# Retries (pack 4): first drafts were reviewed at 128/96/64/48px.
FIT = " Calibration from the previous generation of this exact token: it drew the trident (and part of the tail) reaching far past the edge of the disc, so the token could not be exported. This time draw the naga markedly smaller and tighter: the ENTIRE figure, including the whole trident and every tail coil, fits inside a circle of about two thirds of the disc radius around the disc centre, leaving a wide bare charcoal ring of base plate on every side."
retry('naga-myrmidon', 4, comp=COMP + FIT,
      subject="A naga warrior seen from a steep overhead three-quarter angle, drawn compact and smaller: the upper body of a muscular fair-skinned blond man in slate-grey scale armour with steel pauldrons and dark bracers, both hands gripping a short-shafted trident held upright and close in front of the chest so its bright steel head stays just above his shoulder, rising from a thick coiled serpent tail in bright cobalt blue with a wide pale cream-white banded belly, the coil forming a tight open spiral at the base directly under him. Everything stays tightly clustered in the middle of the disc. Fierce, armoured and complete.")

# Retries (pack 5): the first drafts passed the style gate but were judged too dark at 48px on the real floors
# (masked-body luminance 48.1 for Kyless, 51.9 for the blood mage, both just above the floor of 45).
BRIGHT = " Calibration from the previous generation of this exact token: it passed the disc checks but the figure read as a dark smudge at 48px. This time keep the identity and pose but lift the whole figure by a clear step: broad lit surfaces in the mid-light range, pale rim light and lighter facing planes on the upper-left, nothing near black inside the figure."
retry('kyless', 5, comp=COMP + BRIGHT,
      subject="A haunted human man seen from a steep overhead three-quarter angle, drawn compact: a lean man with warm tan skin and shoulder-length mid-brown hair, a weary corrupted face with glinting pale eyes, in a bright moss-olive tunic with lighter yellow-green highlights and a tan leather belt and mid-brown boots and wrist-wraps, holding a curled cream-coloured spiral horn against his belly with both hands, wreathed by several thick curling tendrils of translucent pale violet-grey smoke with lighter lilac edges that coil up around his shoulders and arms and stay close to his body. Uneasy, sinister and complete, but clearly lit.")
retry('elven-blood-mage', 5, comp=COMP + BRIGHT,
      subject="A grim elven blood mage seen from a steep overhead three-quarter angle: a pale elf with blond hair under a pale steel blue-grey hood with a lighter lining, a long robe in mid-light steel blue-grey with pale silvery-blue highlights on the folds and bold bright crimson blood splatters and a wet bright crimson hem, both hands held open in front at hip height dripping bright red blood in a few droplets that stay near the hands, a hunched menacing lean forward. Sinister, clearly lit and complete.")
