# Pack 4: rak-shor v1 failed the disc_overflow gate (max opaque radius 0.987 > 0.867): the tall bone-crook staff (and its skull head) stood far above the head and crossed the disc rim. Same design and identity, drawn smaller with a short staff held close to the body.
RK_FIT = " Calibration from the previous generation of this exact token: the design was right, but the tall bone-crook staff with its skull-and-crescent head towered far above the figure and crossed the outer rim of the disc. This time keep the same upright old green orc in black-and-violet robes with the spiked collar and bone shoulder pauldrons, but draw the WHOLE figure clearly smaller and the staff SHORT: the bone staff is gripped near its middle at his side and its crook head ends no higher than his own head, well inside the disc, at least a sixth of the disc radius away from the disc edge and never in the upper-right or upper-left corners. Every part of him, the staff head included, sits inside a circle of about two thirds of the disc radius."
retry('rak-shor', 4, comp=COMP + FIT + COMPACT + RK_FIT)

# Pack 5: warmaster-gnarg v1 failed only the base_drift gate (median -9.24, tolerance +-8; radius 0.860 and occupancy passed): the disc came out darker than the reference, mostly on the left and lower side (sector offsets down to -15.9), under the sword and the dark armour. Same design, disc kept at reference lightness all round with no shadow of the armour or sword on it, and the armour a lighter steel value.
GN_DISC = " Calibration from the previous generation of this exact token: the design was right, but the base disc came out clearly DARKER than the style reference, especially along the left and lower left rim and under the sword and legs. This time keep the same braced horizontal-greatsword orc warlord in violet-steel plate, spiked pauldrons and crimson cloak, but render the WHOLE disc, its outer ring band and the plate under the figure, at the style reference's own lightness or a hair lighter, evenly all round, with NO cast shadow, dark contact shadow or ambient darkening of the disc from the armour, the sword or the legs. Make the plate armour a lighter mid-value violet-steel with broad pale lavender-grey highlight planes so the figure does not read as a dark mass on the disc."
retry('warmaster-gnarg', 5, comp=COMP + FIT + COMPACT + GN_DISC)

# Pack 6: orc-assassin v1 passed the gate (drift -3.84, radius 0.860) but is dark: masked-body luminance 48.4 (floor 45, the 9th darkest of 252 tokens) and at 48px the near-black navy hood and jerkin merge into a dark blob with the charcoal disc. Same crouched two-dagger pose and identity, a clearly lighter slate-blue leather and brighter skin.
AS_BRIGHT = " Calibration from the previous generation of this exact token: it passed the gate, but at 48px the near-black navy hood, jerkin and boots merged into one dark blob on the charcoal disc. This time keep the same very low stalking crouch with a dagger in each hand in reverse grip and the masked hooded head, but make the leather clearly LIGHTER: a mid-value slate-blue-grey leather (a light steel-blue on the lit upper-left planes, broad pale highlight planes on the hood, shoulders and knees, pale cream stitching and belts), brighter warm olive-green skin on the forearms and hands, a pale steel dagger blades and bright yellow eyes, so the whole figure is a mid-light value shape well above the disc value with a bright edge on its upper-left side. Never near-black anywhere except the eye slits."
retry('orc-assassin', 6, comp=COMP + FIT + COMPACT + AS_BRIGHT)

# Pack 7: corrupted-war-dog v1 passed the gate (drift +1.39, lum 53.5) but at 48px the near-black fur is a dark blob on the dark disc on every floor. Same identity, a lighter mid charcoal-grey coat, pale ash underbelly and muzzle, bright veins, open-jawed side-on stance so head and legs separate from the body.
DOG_BRIGHT = " Calibration from the previous generation of this exact token: it passed the gate, but at 48px the near-black fur merged into one dark blob on the charcoal disc. This time draw the corrupted war dog SIDE-ON in a snarling lunging stance, seen from the side and slightly above, head turned toward the viewer with the jaws WIDE OPEN showing pale teeth, front legs and hind legs clearly separated from the body with daylight between them, the head clearly separate from the shoulders. Make the coat a MID charcoal-grey, clearly LIGHTER than the disc, with broad pale ash-grey highlight planes on the back, shoulders and haunches, a PALE BONE-WHITE ash underbelly, chest and muzzle, a studded iron collar with a short broken chain, and BRIGHT violet and acid-green glowing corruption veins and cracks across the ribs, shoulders and face, glowing green eyes. Distinct from the shipped brown dire wolf: grey not brown, spiked collar, open jaws, glowing veins. Never near-black anywhere except the mouth interior."
retry('corrupted-war-dog', 7, comp=COMP + FIT + COMPACT + DOG_BRIGHT)

# Pack 8: orc-assassin v2 is still near-black at 48px. Same crouched twin-dagger identity, mid slate-teal leather clearly lighter than the disc, green skin visible on face and arms, twin pale-steel daggers held out from the body.
AS_TEAL = " Calibration from the previous generations of this exact token: they passed the gate, but at 48px the dark leather still merged with the charcoal disc. This time keep the low stalking crouch with a hooded, masked head, but the leather must be a MID slate-TEAL (a light teal-grey on the lit upper-left planes with broad pale highlight planes on the hood, shoulders, forearms and knees), clearly LIGHTER than the disc; the green orc skin clearly visible and bright on the face above the mask and on both bare forearms and hands; TWIN PALE STEEL DAGGERS held OUT AWAY FROM THE BODY, one out to each side at arm's length with the blades bright and clear against the disc, all still inside the inner three quarters of the disc; pale cream belts and stitching, bright yellow eyes. Never near-black anywhere except the eye slits."
retry('orc-assassin', 8, comp=COMP + FIT + COMPACT + AS_TEAL)
