# Pack 6: cute little bunny v1 passed everything but the ear tips: the opaque radius was 0.879 (limit 0.867).
BUNNY_FIT = " Calibration from the previous generation of this exact token: the tips of the very long upright ears reached slightly past the edge of the disc, so the token could not be exported. This time draw the rabbit slightly smaller and lower: the two ears are shorter and held tilted back and slightly folded over at the tips, and the ENTIRE rabbit, ear tips included, fits inside a circle of about seven tenths of the disc radius around the disc centre, leaving a wide bare charcoal ring of base plate on every side."
retry('cute-little-bunny', 6, comp=COMP + FIT + BUNNY_FIT,
      subject="A cute little bunny seen from a steep overhead three-quarter angle: a plump round white-and-pale-grey rabbit sitting and facing the viewer at a slight angle, two ears of moderate length tilted back and folded slightly at the tips with pink insides, big round bright blue eyes, a pink nose, soft fluffy fur with light-grey shading, a fluffy round cotton tail, small pink front paws held up, and just two tiny pointed white teeth showing over the lower lip. Adorable, soft and complete.")

# Pack 7: onilug v1 passed the gate (lum 66.0) but is a thin faint column with a hair-thin staff: about a third of the disc width at 48px.
# Design change: a broad hunched pose with the long arms hanging wide and a short thick staff, so the figure fills the disc.
ONILUG_BOLD = " Calibration from the previous generation of this exact token: it was drawn as a very thin, faint, narrow column with a hair-thin staff, only about a third of the disc wide, unreadable at 48px. This time change the pose to a broad, bold, hunched silhouette: shoulders wide and rolled forward, the head thrust forward, both long arms hanging out and away from the body to each side with big spread clawed hands, one hand gripping a short THICK pale-bone staff held diagonally across the body, and the legs planted wide. The figure is heavy and clearly lit and fills about three quarters of the disc radius around the disc centre in BOTH width and height."
retry('onilug', 7, comp=COMP + FIT + ONILUG_BOLD,
      subject="An onilug seen from a steep overhead three-quarter angle: a gaunt but broad-shouldered hunched humanoid demon of bright mid-light warm grey-mauve leathery skin with clear lighter lilac-grey highlight planes, very long arms hanging wide with big spread clawed hands, legs planted wide, a small bald head thrust forward with bright glowing red eyes and a cruel grin, a short thick pale-bone staff topped with a bright violet crystal gripped diagonally across the body, a ragged pale-grey loincloth. No wings, no horns. Sinister, powerful and complete, clearly lit.")
