"""UA exact unique contracts and immutable AE/AF-style task packs; no runtime edits."""
import hashlib, importlib.util, json, re
from pathlib import Path
from PIL import Image, ImageDraw
HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]; WS=ROOT.parents[2]
spec=importlib.util.spec_from_file_location('ae',HERE.parent/'monster-batch-ae/make_batches.py'); ae=importlib.util.module_from_spec(spec);spec.loader.exec_module(ae)
sha=ae.sha; src=ae.src
D='game/modules/tome/data/'; NPC=D+'gfx/shockbolt/npc/'
ART='game/addons/tome-checker-revised/art/monster-batch-ua/'
FAMILIES={
 'orc-bosses':['orc-berserker','orc-elite-fighter','orc-master-wyrmic','fiery-orc-wyrmic','icy-orc-wyrmic','orc-high-pyromancer','orc-high-cryomancer','golbug','massok'],
 'insect-bosses':['giant-black-ant','giant-army-ant','giant-carpenter-ant','giant-spider','weaver-young','weaver-queen','weaver-matriarch','weaver-patriarch','ungole'],
 'horror-demon-bosses':['abyssal-horror','nightmare-horror','blade-horror','umbral-horror','champion-of-urh-rok','forge-giant','uruivellas','kryl-feijan'],
 'beast-bosses':['warg','wolf','great-wolf','the-withering-thing','norgos-guardian','faeros','ultimate-faeros'],
}
# id, exact native name, source, base file, image, define_as, type, subtype, tall, group, supported brief
ROWS=[
 ('kra-tor',"Kra'Tor the Gluttonous",'general/npcs/orc.lua',None,'humanoid_orc_kra_tor_the_gluttonous.png',None,'humanoid','orc',True,'orc-bosses',"A morbidly obese orc tyrant with greasy pockmarked olive skin, heavy jowls and long oily black hair. Monumental rounded belly wrapped in ornate silver-steel plate with riveted overlapping belly segments and broad engraved shoulder guards; huge granite battleaxe held diagonally close across his chest. Squat broad nearly circular silhouette, exposed pale olive face and hands, bright silver facing planes. No crown. Contrast the lean rank-and-file berserker and upright fighter with extreme corpulence, heavy belly armour and oversized stone axe."),
 ('khulmanar',"Khulmanar, General of Urh'Rok",'general/npcs/major-demon.lua',None,'demon_major_general_of_urh_rok.png',None,'demon','major',True,'horror-demon-bosses',"A massive horned demon GENERAL with broad layered angular blackened steel armour, imposing swept horns and a heavy ridged mantle, gripping ONE massive two-bladed blackened battleaxe across the front. Dark flames are confined to short sculpted amber-white flame ridges on shoulders and axe blades. Broad MID-LIGHT ash-grey metallic upper planes, ivory horn planes and warm pale ember face keep him readable. A commanding broad axe-wielding armoured stance, structurally richer than the silver greatsword champion or bare two-hammer forge smith; no wings, no smoke curtain, no ground flames."),
 ('rungof', 'Rungof the Warg Titan','general/npcs/canine.lua',None,'canine_rungof.png',None,'animal','canine',False,'beast-bosses',"A gigantic cunning WARG TITAN, enormously muscular wolf with a towering thick shaggy shoulder mane, broad scarred muzzle, heavy chest and huge paws. Dense layered mid-light slate-grey fur with broad silver-cream upper highlights, black fur only in local creases. Compact prowling three-quarter crouch, neck high, head turned sideways and tail tightly hooked beside hind legs. No harness, armour or equipment. Exaggerated massive shoulder mane and broad hulking proportions distinguish the titan from shipped slim warg and wolf; one animal only."),
 ('grgglck','Grgglck the Devouring Darkness','general/npcs/horror.lua',None,'horror_eldritch_grgglck.png',None,'horror','eldritch',True,'horror-demon-bosses',"A colossal compact PILE of thick muscular coiled tentacles rising in a domed tiered mass around ONE HUGE round upward-facing razor-toothed mouth. No eyes, humanoid or robe. Midnight charcoal-violet tentacles with BROAD MID-LIGHT slate-lavender raised folds and pale pearl rims, ivory teeth in a gaping central mouth. Thick tentacle loops folded inward, no strand on the outer base ring. Monumental multi-tier dome and thick loops versus nightmare horror flat eight-hook radial maw and abyssal horror eye-covered aquatic tangle; no detached summoned tentacles."),
 ('queen-ant','Queen Ant','general/npcs/ant.lua',None,'insect_ant_queen_ant.png',None,'insect','ant',True,'insect-bosses',"One imposing QUEEN ANT with an enormous swollen pear-shaped segmented egg-bearing abdomen raised high behind a small armored thorax, broad ridged head and huge paired mandibles, six stout jointed legs tucked around the body, two short curved antennae. Wingless. Glossy mid-light red-brown chitin, ivory raised segment seams and pale upper-facing plates. Biological royal grandeur through abdomen proportion, raised thorax carapace and huge mandibles, NOT a crown or human regalia. Compact high domed triangular silhouette unlike low elongated black/army ants or carpenter ant; no eggs, subjects or winged swarm."),
 ('ak-gishil',"Ak'Gishil",'general/npcs/horror.lua',None,'horror_eldritch_ak_gishil.png',None,'horror','eldritch',True,'horror-demon-bosses',"An imposing temporal BLADE HORROR with a narrow upright faceless HUMANOID charcoal body, high tapering blade-like head, two long hooked claw arms and a ragged split tapering lower torso. Three small red-white mineral nodes are embedded on chest and abdomen. Two long SILVER blades attached closely along its shoulders and forearms form an asymmetrical angular sword fan. Broad MID-LIGHT slate-grey dorsal, shoulder, arm and torso planes with pale silver blade edges; deepest black only in local creases. Unlike the shipped blade horror radial spinning mass of swords, this unique has an unmistakable tall narrow torso, pointed head, hanging claw arms and compact vertical blade collar. No portals, detached summoned actors, smoke, halo or tactical marks."),
 ('ninandra','Ninandra, the Great Weaver','general/npcs/spider.lua',None,'spiderkin_spider_ninandra_the_great_weaver.png',None,'spiderkin','spider',True,'insect-bosses',"A huge ancient female SPIDERKIN, one blue and white eight-legged spider: extraordinarily large tall pointed heart-shaped abdomen with tiered ivory ridges and ornate cobalt-blue scroll-like natural chitin patterning, raised small head with paired pale mandibles, thick front legs held like inward curved archways, six rear legs neatly folded inward. Broad ivory-white upper planes, mid-light blue side planes, fully opaque. Distinct high ridged pointed abdomen and formal raised front-leg arches versus low bulbous blue matriarch, weaver queen and slender patriarch; no humanoid torso, cloth, jewellery, fate threads, web scenery or shimmer effect."),
 ('phoenix','Phoenix','general/npcs/bird.lua',None,'animal_bird_phoenix.png','NPC_PHOENIX','animal','bird',False,'beast-bosses',"One majestic fiery PHOENIX bird, proud upright eagle-like body, curved beak, sweeping feather crest and two folded raised wings enclosing the torso in a compact lyre silhouette, long layered flame-shaped tail feathers curled inward beneath it. Opaque sculpted plumage in mid-light red-orange, broad pale golden-cream feather tips and ivory face. Regal long crest, layered wing panels and fan tail, no crown, halo, egg, smoke, base flame, firetrail or ground effects. A recognisable BIRD with physical feathers and beak, unlike faeros upright flame elemental."),
 ('the-shade','The Shade','zones/ruins-kor-pul/npcs.lua',None,'undead_skeleton_the_shade.png','SHADE','undead','skeleton',False,'horror-demon-bosses',None),
 ('ukruk','Ukruk the Fierce','zones/dreadfell-ambush/npcs.lua','general/npcs/orc.lua','humanoid_orc_ukruk_the_fierce.png','UKRUK','humanoid','orc',False,'orc-bosses',"A vicious scarred orc warlord in elaborate overlapping silver-steel massive plate, broad engraved shoulder guards and a short heavy fur-lined mantle. One LONGSWORD held close upright at shoulder and a large thick angular SHIELD bearing a carved abstract native unknown symbol, no letters. Exposed pale olive tusked face, bright silver plate masses. Broad shield-forward commanding compact stance, finer layered regalia than shipped orc fighter, not berserker axe, not Kra'Tor obese stone axe, no crown or floating tactical mark."),
 ('gorbat','Gorbat, Supreme Wyrmic of the Pride','zones/gorbat-pride/npcs.lua','general/npcs/orc-gorbat.lua','humanoid_orc_gorbat__supreme_wyrmic_of_the_pride.png','GORBAT','humanoid','orc',True,'orc-bosses',"A supreme ORC WYRMIC lord with pale green scaly tusked face, clawed hands, TWO small leathery dragon wings folded high behind his shoulders, elaborate dragon-scale harness with ivory dragon-jaw shoulder plates and layered ceremonial scale skirt, gripping the native long dragon-headed POLEARM tucked diagonally across the chest. Broad pale bronze-silver armour highlights and mid-light green scales. Supreme physical regalia through jaw pauldrons, scale layers and a strong winged V-shaped silhouette, structurally richer than shipped fiery/icy/master orc wyrmics. No breath plume, dragon companion, crown or tactical badge."),
 ('grushnak','Grushnak, Battlemaster of the Pride','zones/grushnak-pride/npcs.lua','general/npcs/orc-grushnak.lua','humanoid_orc_grushnak__battlemaster_of_the_pride.png','GRUSHNAK','humanoid','orc',False,'orc-bosses',"An old massive battle-scarred orc BATTLEMASTER with bare pale grey-green tusked head, thick neck, ornate heavy ribbed steel plate, asymmetrical broad layered pauldrons, engraved metal belt and short torn ceremonial war mantle. ONE huge notched broad GREATSWORD, blade held low horizontally across both thighs, massive planted stance and scarred exposed forearms. Bright worn silver upper plates and mid-light skin. More imposing layered regalia than ordinary berserker or fighter; low horizontal two-hand sword, bare head and broad planted stance distinguish Gorbat winged scale-polearm lord and Ukruk upright sword-shield. No crown."),
 ('vor','Vor, Grand Geomancer of the Pride','zones/vor-pride/npcs.lua','general/npcs/orc-vor.lua','humanoid_orc_vor__grand_geomancer_of_the_pride.png','VOR','humanoid','orc',False,'orc-bosses',"An elderly orc GRAND GEOMANCER with wrinkled pale olive face in sumptuous layered multicoloured robes: broad ivory-gold embroidered collar, pale blue and muted crimson heavy panels, wide sculpted sleeves and tiered ash-cream hem. Native physical Crown of the Elements is a low ornate METAL headband with three large inset mineral facets attached to the head, never a floating badge. One short ornate crystal-tipped staff held upright close to his body, free hand raised to cast. Broad mid-light robe planes and pale face. Rich stepped robe architecture, wide collar, mineral staff and attached circlet versus plain hooded pyromancer/cryomancer; no loose ice shards, ground fire, lightning aura or rank graphics."),
]
def block(path,name):
 lines=(WS/(D+path)).read_text().splitlines(); n=next(i for i,l in enumerate(lines) if 'name = "'+name+'"' in l)
 start=max(i for i in range(n+1) if lines[i].startswith('newEntity{')); end=next((i for i in range(n+1,len(lines)) if lines[i].startswith('newEntity{')),len(lines))
 return '\n'.join(lines[start:end]), start+1,end

def build():
 identities=[]
 for id_,name,file,bfile,png,define,typ,sub,tall,group,subject in ROWS:
  leaf,start,end=block(file,name); base=re.search(r'base\s*=\s*"([^"]+)"',leaf)
  pins=[src(file,'name = "'+name+'"')]
  btext=''
  if base:
   bp=bfile or file; pins.append(src(bp,'define_as = "'+base[1]+'"')); lines=(WS/(D+bp)).read_text().splitlines(); n=pins[-1]['line']-1; s=max(i for i in range(n+1) if lines[i].startswith('newEntity{')); e=next((i for i in range(n+1,len(lines)) if lines[i].startswith('newEntity{')),len(lines)); btext='\n'.join(lines[s:e])
  assert not re.search(r'moddable_tile|add_displays|shader\s*=',leaf+btext) if subject else 'shader = "unique_glow"' in leaf
  native=NPC+png
  with Image.open(WS/native) as im:size=list(im.size)
  (HERE/'source').mkdir(exist_ok=True); (HERE/'source'/f'{id_}.lua').write_text('-- Verified leaf and inherited base; source hashes in source-contracts.json\n'+'\n'.join(l.rstrip() for l in leaf.splitlines())+'\n-- INHERITED BASE\n'+'\n'.join(l.rstrip() for l in btext.splitlines()).rstrip()+'\n')
  default='npc/'+typ+'_'+sub+'_'+re.sub('[^a-z0-9]','_',name.lower())+'.png'
  structure='Exactly one nice_tile body at display_h=2/display_y=-1; unique=true admits native tall without native_tall flag.' if tall else 'Flat single 64x64 native image.'
  if not subject:structure='Unsupported actor shader unique_glow; native, no art generation or mapping.'
  identities.append(dict(id=id_,native_name=name,source=pins[0],sources=pins,define_as=define,unique=True,type=typ,subtype=sub,rank=float(re.search(r'rank\s*=\s*([\d.]+)',leaf)[1]),native_tall=tall,native_image='npc/'+png,native_image_path=native,native_image_sha256=sha(native),native_image_size=size,default_image=default,default_image_exists=(WS/(D+'gfx/shockbolt/'+default)).exists(),shader=None if subject else 'unique_glow',moddable_tile=None,add_displays=None,anim=None,nice_tile=('tall=1' if 'tall=1' in leaf else 'explicit single body') if tall else None,add_mos=[dict(image='npc/'+png,display_h=2,display_y=-1)] if tall else None,structure=structure,leaf_source_lines=[start,end],talents=re.findall(r'Talents\.(T_[A-Z0-9_]+)',leaf+btext),verdict='READY' if subject else 'NATIVE shader'))
 auxiliary=[src('zones/heart-gloom/npcs.lua','e.name = rng.table{_t"gloomy'),src('zones/heart-gloom/npcs.lua','e.name = rng.table{_t"dreaming'),src('timed_effects/magical.lua','name = "PHOENIX_EGG"'),src('talents/misc/npcs.lua','list.GRGGLCK_TENTACLE'),src('talents/misc/horrors.lua','--Ak\'Gishil'),src('class/NPC.lua','-- Grab default image name',root='game/modules/tome/'),src('resolvers.lua','function resolvers.calc.nice_tile',root='game/modules/tome/')]
 out=HERE/'source-contracts.json'; out.write_text(json.dumps(dict(schema=1,task='UA first off-list class b uniques/bosses; static source audit; no game launch',identities=identities,auxiliary_sources=auxiliary,rename_policy='Heart Gloom both constructors alter Rungof name/rarity/talents only. Six prefixes preserve same body. Exact per-Rungof alias with constructor/provenance fields; no other unique prefix opt-in.',appearance_policy='Uniques with define_as bind exactly; no define_as is invented for pool uniques. Shader, moddable paper-dolls and extra composites stay native. Shade unique_glow unsupported. Phoenix PHOENIX_EGG changes image; egg remains native and bird token restores on deactivation. Native shader auras and particles are separate from actor shader.',random_boss_policy='Reuse existing captureRandomOrigin/recordRandomOrigin for verified unique bodies, including tall unique precedent; no arbitrary renamed unique admission. Unique temporal clones remain native under existing generic policy.',summon_policy='Queen Ant and Khulmanar summons/escorts draw separate pool bodies; Ninandra summons weaver young/escorts patriarchs. Grgglck tentacle and AkGishil animated blades are separate identities outside UA. Gorbat summons separate rimebark/ritch bodies. No escorts or tactical state baked in art.'),indent=2)+'\n')
 families={}
 for group,ids in FAMILIES.items():
  c=Image.new('RGBA',(384,((len(ids)+2)//3)*128))
  for n,i in enumerate(ids):c.alpha_composite(Image.open(ROOT/'data/gfx/tokens'/f'{i}.png').convert('RGBA'),(n%3*128,n//3*128))
  p=HERE/'refs'/f'{group}.png'; c.save(p); families[group]=dict(path=ART+'refs/'+p.name,sha256=sha(ART+'refs/'+p.name),role='family',note='Shipped siblings in row order: '+', '.join(ids)+'. Structural boss distinction, not colour-only; do not copy their anatomy.')
 c=Image.new('RGBA',(5*220,3*320),(46,50,46,255)); draw=ImageDraw.Draw(c)
 for n,i in enumerate(identities):
  im=Image.open(WS/i['native_image_path']).convert('RGBA').resize((128,256 if i['native_tall'] else 128),Image.Resampling.NEAREST); x=n%5*220;y=n//5*320;draw.text((x+2,y+2),i['id']+(' NATIVE shader' if i['shader'] else ''),fill='white');c.alpha_composite(im,(x+40,y+24))
 c.save(HERE/'refs/native-identities.png')
 packs={}; accepted=[i for i in identities if not i['shader']]
 for row,i in zip(ROWS,identities):
  id_,name,file,bfile,png,define,typ,sub,tall,group,subject=row
  if not subject:continue
  refs=[dict(path=ae.STYLE,sha256=sha(ae.STYLE),role='style',note='Approved neutral disc/camera/light only.'),dict(path=NPC+png,sha256=sha(NPC+png),role='identity',note='Inspected exact native body '+str(i['native_image_size'])),families[group]]
  a=dict(asset_id=id_,native_name=name,scope='UA class b unique; '+i['source']['path']+':'+str(i['source']['line']),sources=i['sources']+auxiliary,references=refs,contrast_dimensions=['silhouette','value','hue'],prompt_fields=dict(subject=subject+ae.CHEAT,contrast='Boss identity through the specified body proportions, structural anatomy, equipment and pose; never just recolour the shipped siblings. No faction rings, health, shield, rank marks, selection, text or numbers.',composition=ae.COMP+ae.DARKFIX,palette='Mid-light broad body masses and pale upper-left highlights. '+ae.DISC+' Whole neutral disc stays at reference lightness; no colour spill.'),kind='creature',max_attempts=2,gate='ready',gate_reason=i['structure']+' Exact static verification only.',render_evidence=[dict(path=ART+'source-contracts.json',sha256=sha(ART+'source-contracts.json'))])
  packs.setdefault(accepted.index(i)//3+1,[]).append(a)
 for n,assets in packs.items():
  p=ROOT/f'art/production/batches/monster-batch-ua-{n}.json'
  if not p.exists():p.write_text(json.dumps(dict(schema=1,batch_id=f'monster-batch-ua-{n}',assets=assets),indent=2)+'\n')
 admitted=json.loads((HERE/'final-admission.json').read_text())['accepted_ids'] if (HERE/'final-admission.json').exists() else [i['id'] for i in accepted]
 (HERE/'catalog.json').write_text(json.dumps([dict(id=i) for i in admitted],indent=2)+'\n')
 (HERE/'catalog.js').write_text('window.monsterCatalog = '+(HERE/'catalog.json').read_text().strip()+';\n')
if __name__=='__main__':build()
