# Retry packs are appended here (never edited in place).

# Pack 5: berethh v1 failed only the base_drift gate (median -8.19, tolerance +-8; radius 0.859 and intrusion 1.2 passed, no other blocking item): the whole disc came out uniformly darker than the reference (all eight sector offsets between -7.0 and -12.2). Same design, disc kept at the style reference's lightness all round.
BE_DISC = " Calibration from the previous generation of this exact token: the design was right, but the base disc came out DARKER than the style reference all the way round, the outer ring band and the plate under the figure alike. This time keep the same standing sideways full-draw thalore archer in the olive-grey hooded cloak with the short recurve bow, but render the WHOLE disc, its outer ring band and the plate under the cloak and boots, at the style reference's own lightness or a hair lighter, evenly all round, with NO cast shadow, dark contact shadow or ambient darkening of the disc from the cloak, the bow or the figure. Make the cloak a lighter sage-olive with broad pale highlight planes."
retry('berethh', 5, comp=COMP + FIT + COMPACT + BRIGHT + BE_DISC)

# Pack 6: borfast v1 failed only the base_drift gate (median -10.61, tolerance +-8; radius 0.859 passed): the disc was much darker than the reference under and beside the figure (sector offsets down to -25.9 at the lower left, under the big shield) and the subject itself is a dark brown-bronze mass at 48px. Same identity and pose, a much lighter pale steel and grey-green subject, disc at reference lightness with no cast shadow.
BO_LIGHT = " Calibration from the previous generation of this exact token: the design was right, but the base disc came out clearly DARKER than the style reference, especially at the lower left under the big round shield and the boots, and the whole figure was a dark brown-bronze mass. This time keep the same squat hunched armoured dwarf ghoul with the big round shield forward, the rusted cage across the chest and the spiked mace raised over the shoulder, but render the WHOLE disc, its outer ring band and the plate under the figure, at the style reference's own lightness or a hair lighter, evenly all round, with NO cast shadow, dark contact shadow or ambient darkening of the disc from the shield, boots or body. Make the whole figure LIGHT: PALE polished steel-silver plate and a pale silver-grey shield with a bright pale rim and a pale boss, PALE sickly grey-green flesh, bone-white beard tuft, cage bars in mid warm grey rather than dark rust, so the figure is a mid-light to light shape well above the disc value with pale edge highlights on its upper-left side. No brown or bronze main masses."
retry('borfast', 6, comp=COMP + FIT + COMPACT + BRIGHT + BO_LIGHT)

# Pack 7: berethh v1 was -8.19 (disc too dark), v2 overshot to +9.63 (disc too light: the "lighter" calibration was over-applied, mostly on the right and upper sectors). Third and last call: same design, disc at the reference lightness, at most a hair lighter, neither darker nor visibly lighter.
BE_DISC3 = " Calibration from two previous generations of this exact token: the first came out slightly DARKER than the style reference and the second came out clearly LIGHTER than the style reference. This time keep the same standing sideways full-draw thalore archer in the olive-grey hooded cloak with the short recurve bow, and render the WHOLE disc, its outer ring band and the plate under the figure, at EXACTLY the style reference's own lightness, evenly all round: at most a hair lighter than the reference, never darker and never visibly lighter, the same charcoal-brown body and the same bronze-grey bevel as the style reference image, with no cast shadow and no brightening. Copy the reference disc's value and bevel faithfully. Keep the sage-olive cloak with broad pale highlight planes."
retry('berethh', 7, comp=COMP + FIT + COMPACT + BRIGHT + BE_DISC3)

# Pack 8: aluin-the-fallen v1 passed the gate (drift -4.26, radius 0.859) but is dark: masked-body luminance 59.1 and at 48px the rust-brown armour and dark red cloak merge into one dark reddish blob with the charcoal disc on every floor. Same hunched slumped pose, dragging axe and red round shield, a much lighter tarnished silver-steel figure.
AL_LIGHT = " Calibration from the previous generation of this exact token: it passed the gate, but at 48px the rust-brown armour, dark red cloak and dark beard merged into one dark reddish blob on the charcoal disc. This time keep the same hunched, slumped, head-bowed knight with the axe dragging low diagonally beside his leg, the small round red shield and the torn cloak, but make the figure clearly LIGHTER: the plate armour a light TARNISHED SILVER-STEEL (mid-light grey with a warm bronze tint only in the recesses and broad pale silver-white highlight planes on the pauldrons, breastplate, helm-less head, knees and gauntlets), only small dull rust stains instead of large dark blood crusts, the cloak a bright CRIMSON-RED (mid value with pinkish-red highlight planes, not maroon), the round shield a bright blood-red with a pale steel rim, a pale steel axe blade with a bright edge, a short grey-brown beard and lighter tan skin, so the whole figure is a mid-light shape well above the disc value with a bright edge along its upper-left side. Never dark brown or near-black anywhere except tiny seams."
retry('aluin-the-fallen', 8, comp=COMP + FIT + COMPACT + BRIGHT + AL_LIGHT)

# Pack 9: companion-warrior v1 passed the gate (drift -4.00, radius 0.860) but is mid-dark: masked-body luminance 62.2 with a russet-brown mass that is low contrast against the disc at 48px. Same low forward lunge, forward sword and teal scarf, a much lighter buff-tan and cream figure.
CW_LIGHT = " Calibration from the previous generation of this exact token: it passed the gate, but the russet-brown leather was a mid-dark mass with low contrast against the charcoal disc at 48px. This time keep the same low forward lunge with the steel longsword thrust forward and the bright teal scarf, but make the whole figure LIGHTER: a pale cream linen shirt showing widely at the chest and sleeves, light BUFF-TAN leather armour with broad pale-yellow highlight planes (not russet or dark brown), light tan bracers and boots, bright sandy-ginger hair, bright polished steel sword blade with a pale edge, the teal scarf bright aqua with pale highlights, so the figure is a mid-light to light shape clearly above the disc value with a bright edge along its upper-left side. Nothing brown darker than a light tan except tiny seams."
retry('companion-warrior', 9, comp=COMP + FIT + COMPACT + BRIGHT + CW_LIGHT)

# Pack 10: aluin-the-fallen v2 passed the gate (drift -0.50) and is clearly better than v1, but the masked-body luminance is still only 64.0 (target 65) and at 48px the brown-grey plate is still a mid-dark mass beside the bright cloak. Third and last call: same pose, a plainly pale silver-steel figure with a bright red cloak and shield.
AL_LIGHT3 = " Calibration from two previous generations of this exact token: both passed the gate, but at 48px the plate armour still read as a dark brown-grey mass. This time keep the same hunched, slumped, head-bowed knight with the axe dragging low diagonally beside his leg, the small round red shield and the torn crimson cloak, but paint the plate armour PALE polished SILVER-STEEL, light grey close to white on all the lit upper-left planes (pauldrons, breastplate, helm-less head, knees, gauntlets), with only light warm-grey shadows and just a few small dull rust-red stains, no brown or bronze main masses at all, the cloak a bright CRIMSON-RED with pinkish highlights, the round shield bright blood-red with a pale silver rim, a pale bright steel axe blade, a short grey-brown beard and a pale tan face. The whole figure must be a light shape clearly above the disc value, with a bright pale edge along its upper-left side."
retry('aluin-the-fallen', 10, comp=COMP + FIT + COMPACT + BRIGHT + AL_LIGHT3)
